### ISSUE TITLE
macOS tar ball "is damaged"

### ISSUE THREAD

**Issue by sunnychanwork** [microsoft/openjdk#10]
**Describe the bug**
MacOSX x64 tar ball on the website is "damaged".

**To Reproduce**
1. Download macosx x64 tarball
2. See the following shell traces:
 
`tar -xzf microsoft-jdk-11.0.10.9-macos-x64.tar.gz`
`sha256sum microsoft-jdk-11.0.10.9-macos-x64.tar.gz`
`2e97bd29ca204d7bbaf26b8c648b1d529a0339e396b1f27a71281d05fb75ab3c  microsoft-jdk-11.0.10.9-macos-x64.tar.gz`
`jdk-11.0.10+9/Contents/Home/bin/java -version`

3. Then MacOSX will pop up with the following dialogue:

> "jdk-11.0.10+9" is damaged and can't be opened. You should move it to the Bin

**Expected behavior**
java -version should gives you java version number

**Screenshots**
![Screenshot 2021-04-07 at 11 07 48 AM](https://user-images.githubusercontent.com/26160927/113804642-90c7d700-9791-11eb-8ccd-fbf99b5f28e4.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version Catalina 10.15.7

**Comment by brunoborges** [comment]
@gdams can you please take a look?

**Comment by gdams** [comment]
those steps work for me:

```bash
➜  tmp tar -xzf microsoft-jdk-11.0.10.9-macos-x64.tar.gz
➜  tmp sha256sum microsoft-jdk-11.0.10.9-macos-x64.tar.gz
2e97bd29ca204d7bbaf26b8c648b1d529a0339e396b1f27a71281d05fb75ab3c  microsoft-jdk-11.0.10.9-macos-x64.tar.gz
➜  tmp jdk-11.0.10+9/Contents/Home/bin/java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment Microsoft-18724 (build 11.0.10+9)
OpenJDK 64-Bit Server VM Microsoft-18724 (build 11.0.10+9, mixed mode)
```

The bundle is signed:
```bash
➜  tmp codesign -dvvv jdk-11.0.10+9 
Executable=/Users/gadams/tmp/jdk-11.0.10+9/Contents/MacOS/libjli.dylib
Identifier=libjli-5555494483682c6b64a23333a53e7c7c6b3c77fb
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=827 flags=0x10000(runtime) hashes=16+5 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=3c96432859f61dad001940f4bc2788bba84253f0
CandidateCDHashFull sha1=3c96432859f61dad001940f4bc2788bba84253f0
CandidateCDHash sha256=d18ba4f3b9a9a98d5e7c1e73638e4718aa4fb1cb
CandidateCDHashFull sha256=d18ba4f3b9a9a98d5e7c1e73638e4718aa4fb1cbc34b0c499a102a071cba2d20
Hash choices=sha1,sha256
CMSDigest=fa2ebd665b104a7b809da4055b8e684c436c398f75c4c36194e6a6af759cb9ee
CMSDigestType=2
CDHash=d18ba4f3b9a9a98d5e7c1e73638e4718aa4fb1cb
Signature size=9061
Authority=Developer ID Application: Microsoft Corporation (UBF8T346G9)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=22 Jan 2021 at 19:24:07
Info.plist=not bound
TeamIdentifier=UBF8T346G9
Runtime Version=10.13.0
Sealed Resources=none
Internal requirements count=1 size=208
```

**Comment by karianna** [comment]
I can reproduce the breaking steps on my Mac OS X Big Sur 11.2.3.

@gdams I see you're prefixing with `tmp` - FYI I'm running directly out of my ~/Downloads directory using iTerm2 and zsh as the shell.

**Comment by karianna** [comment]
A workaround is to use:

`sudo xattr -dr com.apple.quarantine jdk-11.0.10+9/`

**Comment by sunnychanwork** [comment]
I can confirm @karianna workaround works for me.

**Comment by junyuan-z** [comment]
Hi @sunnychanwork , so I take a look at this issue it seems tar.gz files produced by adopt & corretto have the same problem.

![image](https://user-images.githubusercontent.com/53073448/114083102-73fbd400-9863-11eb-905f-ea48f2d520bf.png)

based on my understanding, the `com.apple.quarantine` is added by macOS system automatically for all downloaded files.

**Comment by sunnychanwork** [comment]
I think if there is no way round the "dialogue" then I think we need to document this. The error sounds a bit concerning for people who is new.

**Comment by junyuan-z** [comment]
one thing we notice is the Azul's macOS tar.gz file does not have this problem. we will look into this and see how we can fix this problem. we will keep you updated!

**Comment by junyuan-z** [comment]
we have a fix ready: 

![image](https://user-images.githubusercontent.com/53073448/114595986-e265db00-9c43-11eb-9627-723047350d0f.png)

it will be in our next release.

thanks for reporting this issue!

/CC @brunoborges

**Comment by karianna** [comment]
Released as part of April PSU - see https://www.microsoft.com/openjdk
