### ISSUE TITLE
Minecraft has not started because of an unknown error a popular solution to the problem tlauncher

### ISSUE THREAD

**Issue by truongthanh2002** [microsoft/openjdk#100]
![image](https://user-images.githubusercontent.com/87577915/126042980-567a106d-5af7-407a-90ae-fe0844fd22e0.png)

-try to install another version java
-try to update the video card drivers

i was tried, but it not worked @@

17/07/2021, version Release 1.17.1

**Comment by karianna** [comment]
TLauncher is not supported.  Please use the official Minecraft Launcher.
