### ISSUE TITLE
GAME CRASHED

### ISSUE THREAD

**Issue by truongthanh2002** [microsoft/openjdk#103]
**Describe the bug**

OS & version [e.g. Windows 10, 1822]: Windown 10 19042.1110 20H2

**MSFT Build of OpenJDK Version:**
OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
[hs_err_pid12484.log](https://github.com/microsoft/openjdk/files/6843091/hs_err_pid12484.log)

The output from `java --version`

java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**To Reproduce:**

1. Go to 'Minecraft Launcher'
2. Click on 'Installations'
3. And click 'Play' on version 1.17.1

**Comment by truongthanh2002** [comment]
![image](https://user-images.githubusercontent.com/87577915/126208631-9e0f7524-d865-4b0e-80da-ac3601474ea9.png)
![image](https://user-images.githubusercontent.com/87577915/126208681-90cac401-b050-41a6-9666-5f3969d59139.png)
![image](https://user-images.githubusercontent.com/87577915/126208760-19940cce-dfe9-4da0-9eaa-a9ef355ce1c8.png)

**Comment by karianna** [comment]
Hi @truongthanh2002! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!
