### ISSUE TITLE
Minecraft Crash when i try to turn on shader and joining online server

### ISSUE THREAD

**Issue by kisaragikz** [microsoft/openjdk#107]
CPU : Ryzen 7 5800H
GPU : RTX 3060
![image](https://user-images.githubusercontent.com/87943175/126906160-4ca734e0-2a37-41d0-9544-649bddaaed4c.png)

**Comment by brstaffoMS** [comment]
Hi @kisaragikz! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!
