### ISSUE TITLE
Absturz beim Wechseln der Dimensionen in Minecraft

### ISSUE THREAD

**Issue by dagobertdu94-YT** [microsoft/openjdk#108]
I had shaders on and tried to change the dimension and then the JVM crashed.
Because Pastebin doesn't seem to work for me (my created pastes are instant gone), I uploaded the JVM crashreport in my Dropbox.
So you will find it here: [https://www.dropbox.com/s/3mhe7k22hv6pm85/hs_err_pid7968.log?dl=0](url)

If you need for information, you can ask me.

EDIT: It occured just random, not only if I change the dimension.

**Comment by brstaffoMS** [comment]
Hi @dagobertdu94-YT! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!
