### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by sunnytelugugaming** [microsoft/openjdk#111]
**Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by sunnytelugugaming** [comment]
crassed

**Comment by karianna** [comment]
@sunnytelugugaming - we'll need some more details than this.  Can you tell us what operating system you're using, what you were doing etc?

**Comment by brunoborges** [comment]
@sunnytelugugaming we can reopen if you decide to share more details
