### ISSUE TITLE
Unexpected Computer Crash with particles set to minimal.

### ISSUE THREAD

**Issue by PeterMarse** [microsoft/openjdk#118]
**Describe the bug**
My game was lagging when an enderman was provoked, so I assumed the particles were lagging the game, since there were already a lot of mobs present (it was night). I set particles to minimal, and the lag decreased but was still present. I killed two endermen, and then when I killed a baby zombie, my computer crashed. I don't know how to read the error logs, so I don't know what exactly caused the crash, but I think it has something to do with how the game handles graphics. I've played the game in previous versions and never had such issues, but when I eventually started playing 1.17.1, the issue occured.

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]: Windows 10 , 64 bit Build 19041

**MSFT Build of OpenJDK Version:** 16.0.1+9

The output from `java --version`

**To Reproduce:**

Unknown due to not knowing what caused the behaviour

**Expected behavior**

Unknown due to not knowing what caused the behaviour

**Screenshots, Logs etc**

See attached file
[hs_err_pid21520.log](https://github.com/microsoft/openjdk/files/7024634/hs_err_pid21520.log)

**Additional context**
I had a youtube stream playing in the background, but doing that in the past hasn't caused such issues.

**Comment by karianna** [comment]
Hi @PeterMarse! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!
