### ISSUE TITLE
I keep crashing and I cannot play minecraft whatsoever

### ISSUE THREAD

**Issue by Csanch07** [microsoft/openjdk#121]
A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb00fb5130, pid=6804, tid=1544
#
# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [glfw.dll+0x5130]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Djava.library.path=C:\Users\lxchr\AppData\Roaming\.minecraft\bin\9b47-9d49-f5ac-258e -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.2.3965 -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dlog4j.configurationFile=C:\Users\lxchr\AppData\Roaming\.minecraft\assets\log_configs\client-1.12.xml net.minecraft.client.main.Main --username BlitzDragonan --version 1.17.1 --gameDir C:\Users\lxchr\AppData\Roaming\.minecraft --assetsDir C:\Users\lxchr\AppData\Roaming\.minecraft\assets --assetIndex 1.17 --uuid ab8e2a0aad2d44269f3b17dd9afc2286 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzNTQ0MDA2NjMwMzk3NiIsInN1YiI6IjZhNTZhODA5LTVhNmEtNGI4OC1hZGQzLTBjYTFiMWRiM2Y5OSIsIm5iZiI6MTYyOTg2NjQxMiwiYXV0aCI6IlhCT1giLCJyb2xlcyI6W10sImlzcyI6ImF1dGhlbnRpY2F0aW9uIiwiZXhwIjoxNjI5OTUyODEyLCJpYXQiOjE2Mjk4NjY0MTIsInBsYXRmb3JtIjoiVU5LTk9XTiIsInl1aWQiOiI1OTU1NzYwOWIwMTk2NTQ2YzRjNzA5MGQ1NDY5ODI4ZiJ9.ficoM5238P3ZadFKDOGN1Qhf1ExsOcTZG-O_ns-QhSA --userType msa --versionType release

Host: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz, 12 cores, 15G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1151)
Time: Tue Aug 24 21:40:22 2021 Pacific Daylight Time elapsed time: 6.912208 seconds (0d 0h 0m 6s)

**Comment by karianna** [comment]
Hi @Csanch07! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!
