### ISSUE TITLE
winget installs silently without setting JAVA_HOME

### ISSUE THREAD

**Issue by brunoborges** [microsoft/openjdk#122]
The manifest for winget does not set any parameter, and therefore the MSI installer is executed with default settings. Therefore, PATH is modified after the silent install, and JAVA_HOME is not set.

Should we set JAVA_HOME when silently installed via winget?

manifest: 
https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/OpenJDK/11/11.0.12.7/Microsoft.OpenJDK.11.yaml

**Comment by brunoborges** [comment]
Related poll: https://twitter.com/brunoborges/status/1437468575321640965

**Comment by d3r3kk** [comment]
This is closed and verified. @brunoborges NOTE: The install requires the user to accept elevated permissions during the installation now.

**Comment by brunoborges** [comment]
@d3r3kk was this change applied to all versions or only the latest updates?

**Comment by brunoborges** [comment]
@d3r3kk nevermind, confirmed in the source code that only applies to latest 11 and latest 17. Thanks!
