### ISSUE TITLE
minecraft crash

### ISSUE THREAD

**Issue by olivercool** [microsoft/openjdk#130]
i was playing minecraft on a 2009 computer running windows 10 but suddenly it crashed.
i tried again, but after a few minutes, it crashed again.
any help  preventing this?

**Comment by brunoborges** [comment]
Hi @olivercool,

Any chance you can answer these questions:

1. Are you running a fresh install of Minecraft: Java Edition downloaded from minecraft.net?4
2. Are you using a custom launcher?
3. Are you using mods?
4. Have you done any changes to the installation, such as replaced files, or modified default settings? If yes, please be specific.

**Comment by olivercool** [comment]
Sometimes I replace files for file modification but I didn’t know it can crash the game!What are some stuff I can do to prevent this from happening again?  Sent from Mail for Windows From: Bruno BorgesSent: Sunday, September 26, 2021 5:18 PMTo: microsoft/openjdkCc: olivercool; MentionSubject: Re: [microsoft/openjdk] minecraft crash (#130) Hi @olivercool,Any chance you can answer these questions:Are you running a fresh install of Minecraft: Java Edition downloaded from minecraft.net?4Are you using a custom launcher?Are you using mods?Have you done any changes to the installation, such as replaced files, or modified default settings? If yes, please be specific.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brunoborges** [comment]
If you are making changes to the game, then please report the issue here:

https://bugs.mojang.com/projects/MC/summary
