### ISSUE TITLE
Minecraft error crash report - exit code: 0

### ISSUE THREAD

**Issue by Michamood** [microsoft/openjdk#134]
Every time I launch Minecraft the game loads up, works fine for a few seconds, and then crashes. I don't know what the issue is, and I've tried launching the game a lot of times. It just crashes every single time. Any idea what the issue might be? 
I attached the bug report I got after the game crashed. If you see anything that might help please tell me what to do. 
[Minecraft bug report.docx](https://github.com/microsoft/openjdk/files/7268127/Minecraft.bug.report.docx)
t

**Comment by karianna** [comment]
Hi @Michamood Can you tell us which version of Minecraft you are running, which operating system and if you are running any mods or a modified / different installer?

**Comment by karianna** [comment]
Thank you for the report!
Can you please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary)? Please search for existing reports first; in case you did not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look.
