### ISSUE TITLE
Microsoft Build of OpenJDK 17 not available on Mac Mini M1 (arm64) using Homebrew

### ISSUE THREAD

**Issue by mnriem** [microsoft/openjdk#137]
**Describe the bug**
Microsoft OpenJDK 17 not available on Mac Mini M1 using 'brew install'

**To Reproduce:**
brew install --cask microsoft-jdk17

**Expected behavior**
A successfully installed version of Microsoft OpenJDK 17

**Screenshots, Logs etc**
mac-mini-m1 % brew install --cask microsoft-jdk17
Error: Cask 'microsoft-jdk17' is unavailable: No Cask with this name exists.

**Comment by brunoborges** [comment]
@gdams another question is whether the macOS M1 package is available through Homebrew. Is it?

**Comment by mnriem** [comment]
@gdams That command line works, but was not inline with the tweet. Note I would expect brew to be able to install versions using its @ syntax. And to install the latest and greatest when no @ is used. Thanks for clarifying how to install the current version.
