### ISSUE TITLE
Exit Code 0 Whenever I use my monitor

### ISSUE THREAD

**Issue by Ag3297** [microsoft/openjdk#139]
**Describe the bug**
I am playing on a dell laptop and It runs Minecraft. I am trying to run Minecraft on my monitor which is an acer and the game used to run well, but now it gives me exit code 0.

**Comment by karianna** [comment]
Thank you for the report!
Can you please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary)? Please search for existing reports first; in case you did not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look.
