### ISSUE TITLE
Include LTS in the version output of LTS releases

### ISSUE THREAD

**Issue by brunoborges** [microsoft/openjdk#140]
For OpenJDK 11 and 17, we must include "LTS" somewhere in `java --version`.

For example, Oracle Java 17:

```
Java HotSpot(TM) 64-Bit Server VM
(build 17+35-LTS-2724, mixed mode, sharing)
```

// @karianna @gdams @d3r3kk

**Comment by karianna** [comment]
@brunoborges purpose of this?

**Comment by gdams** [comment]
The challenge we have with doing something like that is we tend to break people's version parsers. What does a non-lts version output look like from Oracle?
