### ISSUE TITLE
Document MSI Installer Switches

### ISSUE THREAD

**Issue by brunoborges** [microsoft/openjdk#143]
The MS Build of OpenJDK for Windows MSI installer is based on the Adoptium code. The installer switches are documented here: https://adoptium.net/installation.html#windows-msi

For quick reference:

Feature | Description
-- | --
FeatureMain | Core Temurin installation (DEFAULT)
FeatureEnvironment | Update the PATH environment variable (DEFAULT)
FeatureJarFileRunWith | Associate .jar files with Java applications (DEFAULT)
FeatureJavaHome | Update the JAVA_HOME environment variable
FeatureOracleJavaSoft | Updates registry keys HKLM\SOFTWARE\JavaSoft\

We should document these under docs.microsoft.com/java/openjdk/install

**Comment by d3r3kk** [comment]
Agreed - we should also add these to our `winget` installer as the optional flags it supports. We can add it as `Capabilities` there. [See here for the schema of this setting.](https://github.com/microsoft/winget-cli/blob/9799443c77bb59e20af8a448964e145f8add6d20/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json#L259)

**Comment by GeoSimos** [comment]
FeatureOracleJavaSoft is not present in the MSI installer packages.
![image](https://github.com/microsoft/openjdk/assets/22078536/1a2bc0bb-abd6-4220-8f02-e5ca0d9d535d)

**Comment by karianna** [comment]
https://github.com/microsoft/openjdk/issues/475

**Comment by GeoSimos** [comment]
> #475

Hi @karianna,
Is this considered fixed? Because you closed #475.

**Comment by GeoSimos** [comment]
> AFAICT #475 has never been closed.

Apologies, my mistake, this is closed and was referenced to my post.
