### ISSUE TITLE
Static Download URLs for Latest Versions

### ISSUE THREAD

**Issue by karianna** [microsoft/openjdk#155]
### Discussed in https://github.com/microsoft/openjdk/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **tcoliver** April 15, 2021</sup>
For automated deployments, having static links available to the latest stable version would be very much appreciated. Ideally the links would be pinned to major versions to limit the possibility of breaking changes. A example use case would be a MECM or Jamf script that downloads and installs the latest OpenJDK distribution though Software Center or Self Service. Any chance of static links for each OS arch being made available?</div>

**Comment by KalleOlaviNiemitalo** [comment]
I see, the static aka.ms download URLs are now listed at <https://docs.microsoft.com/java/openjdk/download-major-urls>
