### ISSUE TITLE
waste bug

### ISSUE THREAD

**Issue by lokeshkumar567p** [microsoft/openjdk#159]
**Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by brunoborges** [comment]
Please reopen once you have more details.
