### ISSUE TITLE
Some minecraft bug that really doesn't want me playing minecraft

### ISSUE THREAD

**Issue by memesdealor** [microsoft/openjdk#173]
bug doesnt let me play minecraft or something lol

desktop is dell precision  its a laptop

windows 10 pro 

# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000005fa32bfa, pid=4880, tid=12132
#
# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.DLL+0xf52bfa]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S Y S T E M  ---------------

OS:
 Windows 10 , 64 bit Build 19041 (10.0.19041.1348)

1. be me
2. open minecraft
3. press play

**Expected behavior**
not being able to play minecraft

**Screenshots, Logs etc**

![image](https://user-images.githubusercontent.com/95186798/143782497-eebbfe6b-5cc1-43fe-9697-e68a6107eb88.png)

**Comment by memesdealor** [comment]
fug u

**Comment by brunoborges** [comment]
@memesdealor mind to confirm whether you are using mods or a custom launcher?

**Comment by memesdealor** [comment]
i was using normal java launcher

**Comment by brunoborges** [comment]
Thanks @memesdealor for confirming. In that case, can you please submit this bug to Mojang's bug tracker?
