### ISSUE TITLE
GitHub issues: Add 'Reported Upstream' label to Minecraft issues when author comments with Mojira issue key

### ISSUE THREAD

**Issue by Marcono1234** [microsoft/openjdk#175]
**Is your feature request related to a problem? Please describe.**
The current GitHub workflow closes Minecraft issues and tells the reporter to report it on the Mojang bug tracker (Mojira), and then to comment the issue key (e.g. `MC-123456`).
Maybe (please correct me if this is wrong) it is easy for you as maintainers to miss when the reporter comments the issue key.

**Describe the solution you'd like**
The GitHub workflow could be extended to detect issue commention creation events, then:
- if the issue is labeled 'Minecraft'
- and the issue does not have the 'Reported Upstream' label yet
- and the comment is created by the issue author
- and the comment contains text which looks like a Mojira issue key

... the workflow could add the 'Reported Upstream' label.

**Describe alternatives you've considered**
Leave it as it is

**Additional context**
Example where the author commented with the issue key: https://github.com/microsoft/openjdk/issues/168#issuecomment-972525413

**Comment by karianna** [comment]
Bad Bot
