### ISSUE TITLE
1.17 AND1.18 NOT WORKING BRUH

### ISSUE THREAD

**Issue by JarJarVader** [microsoft/openjdk#177]
**Describe the bug**
Whenever I try too open 1.17 or 1.18 it doesnt work its shows exit code 0 and crashes all the other versions work properly
**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:
Windows 11 latest
**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by karianna** [comment]
@JarJarVader Thank you for the report!
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
