### ISSUE TITLE
# A fatal error has been detected by the Java Runtime Environment: # #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc85bc5130, pid=5528, tid=14104

### ISSUE THREAD

**Issue by mclau152** [microsoft/openjdk#187]
Hi I have a computer with Intel i7 6700 and geforce GTX 1070 with 16gb RAM and 1TB SSD. I can only play minecraft bedrock edition because when I try to open minecraft java edition it immediately crashes and generates the crash log below:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc85bc5130, pid=5528, tid=14104
#
# JRE version: OpenJDK Runtime Environment Microsoft-28056 (17.0.1+12) (build 17.0.1+12-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-28056 (17.0.1+12-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [glfw.dll+0x5130]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Dos.name=Windows 10 -Dos.version=10.0 -Xss1M -Djava.library.path=C:\Users\LeoMc\AppData\Roaming\.minecraft\bin\e051-c3c6-518c-000f -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.2.7954 -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dlog4j.configurationFile=C:\Users\LeoMc\AppData\Roaming\.minecraft\assets\log_configs\client-1.12.xml net.minecraft.client.main.Main --username TOMCRUZEMISSL --version 1.18.1-pre1 --gameDir C:\Users\LeoMc\AppData\Roaming\.minecraft --assetsDir C:\Users\LeoMc\AppData\Roaming\.minecraft\assets --assetIndex 1.18 --uuid e6baa9a41d0c4089b71cffd8422683bb --accessToken eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzNTQ3Mjg2MTQ5MjU3MCIsImFnZyI6IkFkdWx0Iiwic3ViIjoiZThlZjljN2QtMmQwYS00MWM0LWI3MWQtNTViMDA2ZDIwMGIxIiwibmJmIjoxNjM4ODE3MTAzLCJhdXRoIjoiWEJPWCIsInJvbGVzIjpbXSwiaXNzIjoiYXV0aGVudGljYXRpb24iLCJleHAiOjE2Mzg5MDM1MDMsImlhdCI6MTYzODgxNzEwMywicGxhdGZvcm0iOiJPTkVTVE9SRSJ9.SDdE1j7da6croAtnH_vtlOLcBYl4dL1Mtu69gVIrJdM --clientId ZmYyODBkNzUtMjdjOS00Zjc3LThmMjQtY2JmM2Y3ZWYwYzYw --xuid 2535472861492570 --userType msa --versionType snapshot

Host: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, 8 cores, 15G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1348)
Time: Mon Dec  6 13:58:55 2021 Eastern Standard Time elapsed time: 11.689329 seconds (0d 0h 0m 11s)

**Comment by mclau152** [comment]
I cant submit a bug on Mojang bug tracker because I dont have a Jira
account and when I try to make a Jira account it just says contact your
Jira administrator I dont have a Jira administrator

**Comment by karianna** [comment]
There's a temp outage over there at the moment, please do try again in a few hours or tomorrow.
