### ISSUE TITLE
Minecraft Launcher Bug

### ISSUE THREAD

**Issue by timothyjbrooks** [microsoft/openjdk#190]
**Describe the bug**
_When pressing the play button on the launcher for java edition Minecraft, the launcher appears to go through the whole progress bar and launch but then crashes and says exited with code 0._

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]: _Windows 10_

**MSFT Build of OpenJDK Version:**

openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)

**To Reproduce:**

1. Open Minecraft launcher
1. Go to Minecraft: Java Edition
2. Click on Play button
3. Wait for progress bar to load fully

**Expected behavior**
I expect that the game would run normally as nothing has changed from the last time I played. I was able to play earlier this week just fine and have installed no new programs since.

**Screenshots, Logs etc**
![image](https://user-images.githubusercontent.com/74376887/145317679-cb8faf6b-e94a-4bba-b0fc-950446e8844a.png)

**Additional context**
N/A

**Comment by karianna** [comment]
This may be a case of you needing to have Java 17.0.1 to run Minecraft 1.18
