### ISSUE TITLE
Unable to install Microsoft OpenJDK on a SUSE based distribution

### ISSUE THREAD

**Issue by RDKRACZ** [microsoft/openjdk#199]
**Describe the bug**
Tested on Mageia 8 and openSUSE Leap 15.3

**To Reproduce:**
Add proper ms-openjdk repository to your RPM based OS.

**Screenshots, Logs etc**

```
sudo yum install msopenjdk-17.x86_64
[sudo] password for k0rr: 
Last metadata expiration check: 0:01:58 ago on sob, 25 gru 2021, 18:15:26.
Error: 
 Problem: conflicting requests
  - nothing provides dejavu-sans-fonts needed by msopenjdk-17-17+35-1.x86_64
  - nothing provides dejavu-sans-fonts needed by msopenjdk-17-17.0.1+12_LTS-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by gdams** [comment]
It looks like the dependency is called `dejavu-fonts` on opensuse. We'll have to update the specfile

**Comment by karianna** [comment]
Is that a bug upstream at Adoptium as well?

**Comment by gdams** [comment]
> Is that a bug upstream at Adoptium as well?

No it isn't, both the old style (that Msft uses) https://github.com/adoptium/installer/blob/master/linux/suse-rpm/config/jdk-11-hotspot/dependencies.txt#L4 and the new style have the font correctly defined

**Comment by gdams** [comment]
@RDKRACZ can you please share the commands that you used to add the repository to your environment? 

From what I can see we don't currently have a SUSE based RPM published to packages.microsoft.com (https://packages.microsoft.com/opensuse/15/prod/)

The SUSE-based RPM is what you'll need which we can easily upload

**Comment by brunoborges** [comment]
@gdams hey george, is this fixed in the January update?

**Comment by brunoborges** [comment]
@gdams Is this fixed now in the April update?

**Comment by d3r3kk** [comment]
We do not provide a SUSE based RPM _yet_. As we build out our infra we will add other distributions of Linux package managers, but we have to keep the scope tight while we learn to walk. It is possible we could target July PSU if we'd like to get one out for then, but there might be other priorities in the way. @brunoborges and @karianna can help me schedule this work.

**Comment by brunoborges** [comment]
We will track this as per #389
