### ISSUE TITLE
Consider using GitHub Releases in this repo to announce new releases.

### ISSUE THREAD

**Issue by karianna** [microsoft/openjdk#208]
@crd477 thanks for the suggestion. We can certainly consider using GitHub Releases in this repo to announce new releases. We will explore that for the January PSU if possible.

_Originally posted by @brunoborges in https://github.com/microsoft/openjdk/discussions/34#discussioncomment-1951313_

**Comment by brunoborges** [comment]
Here's the release page we will be using: https://github.com/microsoft/openjdk/releases/tag/untagged-6aed32b54f44432fccbf

**Comment by brunoborges** [comment]
Alright, release for the January updates has been submitted. Those watching this repo get a notification. 

https://github.com/microsoft/openjdk/releases

**Comment by crd477** [comment]
I noticed that there have been subsequent releases that didn't go through this process.  As a result, I didn't get notified.  Was this unintentional?
Thank you!

**Comment by karianna** [comment]
@brunoborges - Possible slip in our process?
