### ISSUE TITLE
Idk know what to do

### ISSUE THREAD

**Issue by Trickzs** [microsoft/openjdk#216]
When ever i play mc mods on a server the game crashes and this comes idk how to explain it or what kind of bug it is or what to do but ill just send the file that shows when it happens
[hs_err_pid16724.log](https://github.com/microsoft/openjdk/files/8008084/hs_err_pid16724.log)

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
