### ISSUE TITLE
Cent OS 8 repository only has msopenjdk-11 in it, add jdk 17 to it.

### ISSUE THREAD

**Issue by RDKRACZ** [microsoft/openjdk#217]
**Describe the bug**
I followed [the official guide](https://docs.microsoft.com/en-us/java/openjdk/install#install-on-centos-7-rpm) and added the repository but I changed the `centos/7/packages` part to `centos/8/packages` after confirming [it does exist on the server](https://packages.microsoft.com/config/centos/8/).

**Expected behavior**
Cent OS 8 repository not missing msopenjdk-17

**Screenshots, Logs etc**
`dnf se msopenjdk`
```
==================== Summary & Name Matched: microsoft, jdk ====================
msopenjdk-11.x86_64 : OpenJDK Development Kit 11 (JDK) with Hotspot by Microsoft
```

**Comment by brunoborges** [comment]
CentOS has reached EOL, and it was never an LTS release. That is why we did not publish a package to that repo.

Please see #220 for further info.
