### ISSUE TITLE
Missing repository for Fedora 35

### ISSUE THREAD

**Issue by RDKRACZ** [microsoft/openjdk#218]
Fedora 35 was released November 2, 2021. Your server only has repository for Fedora version up to 34. https://packages.microsoft.com/config/fedora

**Comment by brunoborges** [comment]
@bureado do you have any info on this?

**Comment by orgcontrib** [comment]
We're a month away from [F36 ](https://fedorapeople.org/groups/schedule/f-36/f-36-key-tasks.html)and still nothing.
😉@karianna

**Comment by mbearup** [comment]
@RDKRACZ apologies for the delayed response here.
- The Fedora 35 repo was created [here](https://packages.microsoft.com/yumrepos/microsoft-fedora35-prod/) but regretably the friendly name [here](https://packages.microsoft.com/fedora/35/prod/) was not populated. This has been resolved.
- The Fedora 36 repo has also been created. Thank you @orgcontrib for the reminder to keep pace with distro revisions.
- For issues with the package repos (such as this) you can file an issue with our github repo at https://github.com/microsoft/linux-package-repositories. The JDK team can help with package-specific issues (i.e. broken dependencies, runtime failures), but has no capacity to assist with missing repositories.
