### ISSUE TITLE
Install guide is missing some supported Linux distributions

### ISSUE THREAD

**Issue by RDKRACZ** [microsoft/openjdk#219]
Here https://docs.microsoft.com/en-us/java/openjdk/install#install-on-centos-7-rpm the only described Linux distributions are Ubuntu 18.04 and 20.04, Debian 9 and 10, Cent OS 7 but [the server](https://packages.microsoft.com/config/) has packages for distributions mentioned above and additionally for:

Ubuntu, from 14.04 to 22.04; Debian 8, 11 and Stretch; Cent OS 6 and 8; Fedora, from 26 to 34; openSUSE 12, 15, 42.3; rhel, from 6 to 8; sles 11, 12 and 15.

I believe some of them (e.g. Fedora) are officially supported by You and should be described in this document.

**Comment by brunoborges** [comment]
I'm closing this as we are not currently planning to expand the test matrix and package availability.

We will continue to provide commercial support as per our policy [1].

https://docs.microsoft.com/en-us/java/openjdk/support#operating-systems-and-linux-distributions
