### ISSUE TITLE
Error, pls solve

### ISSUE THREAD

**Issue by AatmanJain** [microsoft/openjdk#226]
Hello guys I was facing issues while trying to launch Salwyrr, here is the entire process. I have a linux device running ubuntu.

aj@gudmann-Latitude-E5530-non-vPro:~/Downloads$ java -jar SalwyrrMinecraftLauncher4.jar
Get update files
Get local files
Parse update files
Checking local files...
Start unzip
Update finished in 8.568 seconds
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xmx512m -cp /home/aj/.Salwyrr/launcher/launcher.jar fr.salwyrr.launcher.frames.Main --salwyrr salwyrr 
aj@gudmann-Latitude-E5530-non-vPro:~/Downloads$ starting...
Cleaning
Get update files
starting...
Get local files
Checking download files...
Checking local files...
starting...
Start download...
java.nio.file.NoSuchFileException: /home/aj/.Salwyrr/launcher/temp/jre16.zip.001.download0
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
	at lIIIII.<init>(SalwyrrUpdate.java:282)
	at lllIll.llIllIII(PanelPlay.java:258)
	at java.base/java.lang.Thread.run(Thread.java:829)

Get zip size...
-> Total zip size: 769.6 MB
Start unzip...
-> Unzip /home/aj/.Salwyrr/launcher/temp/jre16.zip.003 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/jre.zip.005 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/cef.zip to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/jre.zip.002 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/jre16.zip.002 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/jre.zip.001 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/lwjgl2arm32.zip to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/b_cef.zip to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/lang.zip to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/libs.zip to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/emojis.zip to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/jre.zip.004 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/jre.zip.003 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/temp/slw_assets.zip to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.008 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0017 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.003 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0019 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0020 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.007 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0012 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.004 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0014 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0018 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0015 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.006 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.005 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.002 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0016 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.001 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0011 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0013 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.0010 to /home/aj/.Salwyrr/launcher
-> Unzip /home/aj/.Salwyrr/launcher/versions/assets/1.18/assets.zip.009 to /home/aj/.Salwyrr/launcher
Update finished in 381.397 seconds
os.arch -> amd64
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007feaa3e6fce6, pid=3583, tid=3587
#
# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjimage.so+0x3ce6]# An error report file with more information is saved as:
# /home/aj/.Salwyrr/hs_err_pid3583.log
  ImageDecompressor::decompress_resource(unsigned char*, unsigned char*, unsigned long long, ImageStrings const*, Endian*)+0x26
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/aj/.Salwyrr/core.3583)
#
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
#

**Comment by karianna** [comment]
Hi there, wJava 16 is out of support.  Are you able to try our latest 17.0.2 build?

**Comment by FinnT730** [comment]
They are using a pirated launcher / making one.

**Comment by FinnT730** [comment]
Thanks!
