### ISSUE TITLE
Builds unavailable for some Debian versions

### ISSUE THREAD

**Issue by nopeinomicon** [microsoft/openjdk#244]
**Describe the bug**
The Microsoft repositories do not have OpenJDK packages for Debian 11 or unstable/sid

Debian 11 especially is the current version of the distribution so it would do a lot of good for Microsoft to push their OpenJDK builds to it. As far as sid goes, it's probably a less wide community good, but would still help for those like myself who use it as a daily driver, and those developing for Debian.

**Desktop (please complete the following information):**

OS & version: Debian sid/bookworm (current)

**Comment by brunoborges** [comment]
Our `tar.gz` packages should work just fine on most Linux boxes, including Debian 11.

`.deb` files on the other hand, are mostly for LTS versions.

**Comment by nopeinomicon** [comment]
Understandable, though still, it would be good if it was available for Debian 11 as that is an LTS version of Debian for all intents and purposes, and it would make it a lot easier on users to install and keep up to date.

**Comment by brunoborges** [comment]
According to the Debian Wiki, version 11 is a "Future LTS" release, scheduled for July 2024 to July 2026.

https://wiki.debian.org/LTS

Now, we may change things on our end, we are just not promising anything for now, as we are currently following Debian's schedule.

**Comment by nopeinomicon** [comment]
@brunoborges To be fair, Debian’s definition of LTS posted there is the just extended security support period they provide for a Debian release on mainstream architectures after mainline support has ended. So technically every Debian system on an architecture covered by their LTS team is supported long term in the way that an Ubuntu or other distro LTS is, no matter if Debian considers it a current LTS system. 

Following Debian’s definition of a current LTS for this purpose basically means only supporting a system that’s already halfway through its lifecycle.

If you still stick with that decision I’m not really going to complain, but I figured I’d at least make sure that detail was taken into account.
