### ISSUE TITLE
[Help] GpgKey Url Error when Upgrade JDK Mariner

### ISSUE THREAD

**Issue by Incarnation-p-lee** [microsoft/openjdk#245]
**Describe the bug**
Hi all, could like to ask some help when `tdnf upgrade -y` from **mcr.microsoft.com/openjdk/jdk:11-mariner**. It reported error as below, could you please help to insight me on how to resolve this?

The option `--nogpgcheck` can workaround this issue but looks it is not recommended.

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]: Linux

**MSFT Build of OpenJDK Version:** mcr.microsoft.com/openjdk/jdk:11-mariner

The output from `java --version`
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)

**To Reproduce:**

1. `docker run -ti mcr.microsoft.com/openjdk/jdk:11-mariner bash`
2. `tdnf upgrade -y`

**Expected behavior**
End succeeded.

**Screenshots, Logs etc**
![image](https://user-images.githubusercontent.com/6782002/159837705-34451f19-450b-40bb-9855-5b6008963997.png)

**Additional context**

**Comment by brunoborges** [comment]
Thanks for reporting this. We will look into it.

We also identified a problem where the JDK 11 package is not properly updating on Mariner. The latest version is `11.0.14.1` while the system thinks that's an older version.

**Comment by brunoborges** [comment]
@Incarnation-p-lee can you please double check if your issue is related to this discussion? 

https://github.com/microsoft/openjdk/discussions/206#discussioncomment-2153201

**Comment by brunoborges** [comment]
@d3r3kk can your team double check this one please?

**Comment by d3r3kk** [comment]
Just ran the following:

```bash
PS C:\Users\d3r3kk> docker run -ti mcr.microsoft.com/openjdk/jdk:11-mariner bash
root [ / ]# tdnf upgrade -y
Loaded plugin: tdnfrepogpgcheck
Refreshing metadata for: 'CBL-Mariner Official Extras 2.0 x86_64'
Refreshing metadata for: 'CBL-Mariner Official Base 2.0 x86_64'
Refreshing metadata for: 'CBL-Mariner Official Microsoft 2.0 x86_64'
Refreshing metadata for: 'packages-microsoft-com-prod'
Nothing to do.soft-com-prod              84752   100%
root [ / ]# tdnf downgrade msopenjdk-11
Loaded plugin: tdnfrepogpgcheck

Downgrading:
msopenjdk-11                         x86_64             11.0.16.1-1              mariner-official-microsoft 308.81M 323815839

Total installed size: 308.81M 323815839
Is this ok [y/N]: y

Downloading:
msopenjdk-11                         193183373   100%
Testing transaction
Running transaction
Installing/Updating: msopenjdk-11-11.0.16.1-1.x86_64
Removing: msopenjdk-11-11.0.17-1.x86_64

Complete!
root [ / ]# tdnf upgrade -y
Loaded plugin: tdnfrepogpgcheck

Upgrading:
msopenjdk-11                         x86_64             11.0.17-1                mariner-official-microsoft 309.37M 324400663

Total installed size: 309.37M 324400663

Downloading:
msopenjdk-11                         193498166   100%
Testing transaction
Running transaction
Installing/Updating: msopenjdk-11-11.0.17-1.x86_64
Removing: msopenjdk-11-11.0.16.1-1.x86_64

Complete!
root [ / ]#
```


This seems to be resolved from what I can see. @brunoborges I leave it to you to close it out.
