### ISSUE TITLE
Every time i join it says Crashed

### ISSUE THREAD

**Issue by Strangerganger** [microsoft/openjdk#248]
a Crashing bug

1.18.2

a

java

**Expected behavior**
When ever i try going in it says Crashed randomly and error code: 0

"None"

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
