### ISSUE TITLE
Tlauncher crashes

### ISSUE THREAD

**Issue by DhruvRp** [microsoft/openjdk#250]
**
[hs_err_pid8536.log](https://github.com/microsoft/openjdk/files/8410328/hs_err_pid8536.log)
Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by DhruvRp** [comment]
It shows error code 1 I have tried all possible fix but none work

**Comment by karianna** [comment]
We don't support unofficial launchers I'm afraid.
