### ISSUE TITLE
Game Crash - Activating piston w/ Mods installed

### ISSUE THREAD

**Issue by melissa-24** [microsoft/openjdk#252]
**Describe the bug**
While trying to activate a modded piston with a remote control the game crashed.  I am no longer able to get into this specific world.  However we were able to recreate the crash on a dummy world, after deleting the session.lock file to clear the running instance on the dummy world we were able to get back into that one and noticed the inventory was now reset but the base parts of the structure that caused the crash were still there.  We believe if we can reset the inventory on the good world (or another dummy  one for testing) that this may solve getting into the world.  Much of the below information requested can be found in the linked crash log.

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:
Windows 10

**MSFT Build of OpenJDK Version:** 
Please see crash log linked below

The output from `java --version`

**To Reproduce:**

Video of reproducing the crash and any other supporting video(s) link(s)
https://drive.google.com/file/d/1ZUzU7wpxSnjaNs7FE8n1raav4occ5Ryg/view?usp=sharing
https://drive.google.com/file/d/1T1yeHKoskfeCHH7TOD5Hn_xKQwsyQ1nx/view?usp=sharing

**Expected behavior**
Game should not crash

**Screenshots, Logs etc**
The crash log link is as follows https://drive.google.com/file/d/1ec0ptB8dM34omT935k2WdsQ0iAYF2Bkh/view?usp=sharing

**Additional context**

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
