### ISSUE TITLE
Keeps crashing on unmodded java

### ISSUE THREAD

**Issue by BouncyBonBon** [microsoft/openjdk#253]
Despite not having mod's or deleted files, the crash log always comes up with 'missing file' or 'file gave outcome of -1'
Please help!

https://pastebin.com/jj1ri7Z5

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
