### ISSUE TITLE
Is there a general rule to get the name of the folder inside the zip?

### ISSUE THREAD

**Issue by Vixb1122** [microsoft/openjdk#258]
[microsoft-jdk-17.35.1-windows-x64.zip](https://aka.ms/download-jdk/microsoft-jdk-17.35.1-windows-x64.zip)  → jdk-17+35
[microsoft-jdk-17.0.2.8.1-windows-x64.zip](https://aka.ms/download-jdk/microsoft-jdk-17.0.2.8.1-windows-x64.zip) → jdk-17.0.2+8
[microsoft-jdk-17.0.3-windows-x64.zip](https://aka.ms/download-jdk/microsoft-jdk-17.0.3-windows-x64.zip) → jdk-17.0.3+7

How i can convert 17.0.3 to 17.0.3+7?

**Comment by d3r3kk** [comment]
How would you like to? 

I see other vendors (Adoptium) using `_7` in the file name to denote the `+7` suffix of the folder name.

What would your expectations be?

**Comment by Vixb1122** [comment]
> How would you like to?

If you use [Scoop](https://github.com/ScoopInstaller/Scoop) to manage jdk, you need to know the name of the folder inside the zip.

combine https://github.com/ScoopInstaller/Java/blob/master/bucket/microsoft-lts-jdk.json#L17-L20 
and https://github.com/ScoopInstaller/Java/blob/master/bucket/microsoft-lts-jdk.json#L30 
to get https://github.com/ScoopInstaller/Java/blob/master/bucket/microsoft-lts-jdk.json#L12

> I see other vendors (Adoptium) using `_7` in the file name to denote the `+7` suffix of the folder name.
> 
> What would your expectations be?

Rename [microsoft-jdk-17.0.3-windows-x64.zip](https://aka.ms/download-jdk/microsoft-jdk-17.0.3-windows-x64.zip) to [microsoft-jdk-17.0.3.7.1-windows-x64.zip](https://aka.ms/download-jdk/microsoft-jdk-17.0.3.7.1-windows-x64.zip)

Or rename the name of the folder inside the zip from `jdk-17.0.3+7` to `jdk-17+0`.

**Comment by brunoborges** [comment]
You should be able to list the entries in a Zip file, and get the name of the folder. With a bit of bash script, you should be able to do the following:

```bash
$ wget https://aka.ms/download-jdk/microsoft-jdk-17.0.3-windows-x64.zip
--2022-04-29 08:47:03--  https://aka.ms/download-jdk/microsoft-jdk-17.0.3-windows-x64.zip
Resolving aka.ms (aka.ms)... 23.32.88.234
Connecting to aka.ms (aka.ms)|23.32.88.234|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.visualstudio.microsoft.com/download/pr/2b0e8f85-f37f-4467-9076-770dacd8b0cb/c8d8a2cbf8e1bbf181998cf251b3559a/microsoft-jdk-17.0.3-windows-x64.zip [following]
--2022-04-29 08:47:03--  https://download.visualstudio.microsoft.com/download/pr/2b0e8f85-f37f-4467-9076-770dacd8b0cb/c8d8a2cbf8e1bbf181998cf251b3559a/microsoft-jdk-17.0.3-windows-x64.zip
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 93.184.215.201, 2606:2800:11f:7de:d31:7db:168f:1225
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|93.184.215.201|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 185543457 (177M) [application/octet-stream]
Saving to: ‘microsoft-jdk-17.0.3-windows-x64.zip’

microsoft-jdk-17.0.3-windows-x64.zip                       100%[=======================================================================================================================================>] 176.95M   115MB/s    in 1.5s    

2022-04-29 08:47:06 (115 MB/s) - ‘microsoft-jdk-17.0.3-windows-x64.zip’ saved [185543457/185543457]
$ zip -sf microsoft-jdk-17.0.3-windows-x64.zip | sed -n 2p | xargs
jdk-17.0.3+7/
```
