### ISSUE TITLE
Microsoft build of OpenJDK is not available for Ubuntu 22.04 via the package server at packages.microsoft.com

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/openjdk#262]
### Discussed in https://github.com/microsoft/openjdk/discussions/261

<div type='discussions-op-text'>

<sup>Originally posted by **Lolothepro** May  3, 2022</sup>
Microsoft OpenJDK is not available for Ubuntu 22.04 as a package (msopenjdk-17), contrary to what the manual says (https://docs.microsoft.com/en-us/java/openjdk/install).
So my question is:
Do you plan to add the package to the Microsoft repository?</div>

**Comment by karianna** [comment]
@brunoborges for an official position on this.

**Comment by karianna** [comment]
Docs will also need an update for when we do this (it's LTS, so we should).
