### ISSUE TITLE
theres a bug that it automatically closes and it wanted me to change into windows 7

### ISSUE THREAD

**Issue by vincentvald** [microsoft/openjdk#266]
**Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by brunoborges** [comment]
Can you please provide a description of the problem?

**Comment by karianna** [comment]
Closing due to no additional info.
