### ISSUE TITLE
Microsoft OpenJDK Latest Version?

### ISSUE THREAD

**Issue by PowerUser1234** [microsoft/openjdk#268]
I notice that the multiplatform free downloads of the Microsoft Java OpenJDK seem to go up to version 17.

Will there be a version 18, or later? Does 17 include the Modules system, and their ability to shut down the reflection mechanism?

**Comment by karianna** [comment]
@PowerUser1234 At this stage we are only producing the LTS builds and recommend that you go to our partner Eclipse Adoptium (adoptium.net) where we contribute to producing non LTS builds :-).  Please do let us know if MSFT Build of OpenjDK is a strict requirement for you in this case.
