### ISSUE TITLE
Java error causing MC to crash:  A fatal error has been detected by the Java Runtime Environment: 425037

### ISSUE THREAD

**Issue by parkcity57** [microsoft/openjdk#284]
MC continues to crash on me with multiple Java errors
[hs_err_pid8044.log](https://github.com/microsoft/openjdk/files/8942161/hs_err_pid8044.log)
.

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
