### ISSUE TITLE
Java error causing MC to crash: A fatal error has been detected by the Java. 

### ISSUE THREAD

**Issue by Pacelf158** [microsoft/openjdk#285]
MC keeps crashing and complaining about heap dump problems or something.

[hs_err_pid4308.log](https://github.com/microsoft/openjdk/files/8956125/hs_err_pid4308.log)

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
