### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa41193416, pid=3576, tid=18088

### ISSUE THREAD

**Issue by imouse1** [microsoft/openjdk#287]
The body of the text said if I wanted to submit a bug report to come here.  I've never had a pop-up like this before.  I was restarting my computer to do the latest updates and then this came up after the restart.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0
[hs_err_pid3576.log](https://github.com/microsoft/openjdk/files/8968153/hs_err_pid3576.log)
0

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

**Comment by karianna** [comment]
Hmm, very odd I suspect you saw an old cache error message them.  The log file posted was from a minecraft run.
