### ISSUE TITLE
java crash 

### ISSUE THREAD

**Issue by olivda** [microsoft/openjdk#290]
**Describe the bug**
i have issue with using minecraft forge and ask help to forge forum 
they answer was java crash itself and i have to report this to here
so i write bug report here
**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:
	Windows 10 Home 21H2
**MSFT Build of OpenJDK Version:**

The output from `java --version`
java version "17.0.4" 2022-07-19 LTS
Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)
**To Reproduce:**
download minecraft and forge 1.18.2(any [version)](url)
and play it twice(first for complete installation
and it occur

**Expected behavior**
expected error is game is not played and error occur with exit code -1073741819
**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.
[error.log](https://github.com/microsoft/openjdk/files/9149577/error.log)

**Comment by olivda** [comment]
in the mojang bug tracker they say update the java but i have latest java 17

**Comment by karianna** [comment]
The error log file indicates that your version of Minecraft is using 17.0.1.  the latest 1.19.x series uses 17.0.3.

You may be able to force Minecraft to use your installed 17.0.4 by adding that to the front of your PATH
