### ISSUE TITLE
Exit code error 6 [Macbook pro]

### ISSUE THREAD

**Issue by Poulos38** [microsoft/openjdk#297]
Hello everyone !

Anytime I want to launch the game (version 1.19.1), it crashes and I get a exit code "6"

I'm on macOS Monterey 12.3.1

here the log error : [hs_err_pid2784.log](https://github.com/microsoft/openjdk/files/9203704/hs_err_pid2784.log)
<img width="1000" alt="Capture d’écran 2022-07-27 à 23 34 17" src="https://user-images.githubusercontent.com/110134387/181376503-82ca4d00-b730-4418-89f0-04b1f5a47416.png">

Thanks for your help

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
