### ISSUE TITLE
MSFT Build of OpenJDK 17.0.3 (Windows on Arm) not opening JAR file (host is Mac OS X running parallels)

### ISSUE THREAD

**Issue by karianna** [microsoft/openjdk#298]
Hi:

Windows 11 ARM (running in parallels on Mac M1 Max).

Installed MS Java 17 from MS:

C:\tmp>java -version
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Microsoft-32931 (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Microsoft-32931 (build 17.0.3+7-LTS, mixed mode)

C:\tmp>echo %JAVA_HOME%
C:\Program Files (Arm)\Microsoft\jdk-17.0.3.7-hotspot\

My problem is trying to open a Jar file. Nothing happens. No error but the task manager show a couple of Java processes that immediately close.

I can run simple java programs:
c:\tmp>java sample3.java
Hello World!

But trying to open a jar produces no results.

C:\tmp>java -jar BBjBaristaAddonDemos2202_07-06-2022_1802.jar

Any help will be greatly appreciated.

ES

_Originally posted by @edgarjsanchez in https://github.com/microsoft/openjdk/discussions/296_

**Comment by brunoborges** [comment]
@edgarjsanchez any chance you can share the JAR with us? If not, can you please run `java -verbose:class -jar <jarfile>` ?

**Comment by edgarjsanchez** [comment]
Hi:

It's a large jar but it's shareable.

https://drive.google.com/file/d/1gXGRfi0SeGfWYent95xyrOxUzVcdUqkP/view?usp=sharing

[image: image.png]

Using the verbose stops at the shown line.

FYI, I ended up using the x64 version of Java in order to be able to run
the jar.

Regards,

Edgar

**Comment by karianna** [comment]
@edgarjsanchez I just tried running this on my Intel Mac with Java 17 and the app pops up a splash screen stating that only Java 11 is supported.  I think you'll need to ask the authors of the program for their plans to upgrade to Java 17.

**Comment by Mceberhart11** [comment]
> @edgarjsanchez I just tried running this on my Intel Mac with Java 17 and the app pops up a splash screen stating that only Java 11 is supported. I think you'll need to ask the authors of the program for their plans to upgrade to Java 17.

**Comment by karianna** [comment]
Closing due to no response and it's a 3rd party support issue.
