### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment 17.0.3+7

### ISSUE THREAD

**Issue by BuckyBarnes1937** [microsoft/openjdk#304]
**Describe the bug**
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9d33acae1, pid=8496, tid=1040

# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0xcae1]

# No core dump will be written. Minidumps are not enabled by default on client versions of Windows

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:
 Windows 11 , 64 bit Build 22000

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by karianna** [comment]
@BuckyBarnes1937 Can you try with our recently release 17.0.4?

**Comment by karianna** [comment]
@BuckyBarnes1937 Can you also let us know if this is Minecraft related?
