### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by Lacaca12** [microsoft/openjdk#305]
**Describe the bug**
When ever i try to launch java on the launcher it crashes and says error code 1
**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:
Windows 10
**MSFT Build of OpenJDK Version:**
OpenJDK
The output from `java --version`
1.19.2
**To Reproduce:**

**Expected behavior**
the game would run properly
**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.
![Screenshot (1)](https://user-images.githubusercontent.com/102488070/184410997-72b73709-4527-46b5-bdb6-f4991c0564cb.png)
Ive tryed many things but i cant find a way to fix it

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
