### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by CandyCaneChoas** [microsoft/openjdk#306]
**Describe the bug**
 I don't know what it is im trying to figure that out.

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:Microsoft-32931

**MSFT Build of OpenJDK Version:**OpenJDK 64-Bit Server

A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe5a5d2fb0, pid=25364, tid=28180
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [ig7icd64.dll+0x452fb0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#

**Comment by karianna** [comment]
@CandyCaneChoas Is this running Minecraft?

**Comment by CandyCaneChoas** [comment]
yes it runs fine then closes when i open a server or play single player

**Comment by CandyCaneChoas** [comment]
when i go to play minecraft it runs fine without shaders. it also runs fine with internal shaders but when i use like lowend shaders or something like that it crashs my game wether it be in single or a server. its just when i use shaders my game dies.

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the Mojang bug tracker. Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the Mojang bug tracker. Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
