### ISSUE TITLE
OpenJDK page is broken

### ISSUE THREAD

**Issue by eddynaka** [microsoft/openjdk#31]
Hi,

Using Chrome/Edge in Windows, the page is broken in the header and footer:
![image](https://user-images.githubusercontent.com/16199012/114872522-cf344600-9dd0-11eb-86c4-2091f95bc414.png)
![image](https://user-images.githubusercontent.com/16199012/114872548-d6f3ea80-9dd0-11eb-83f0-3a03ee3a7454.png)

Page that i'm using to view that: https://www.microsoft.com/openjdk

**Comment by karianna** [comment]
@eddynaka thanks for getting in touch!  Can you post your exact version of Chrome/Edge and your exact O/S version as well?  We'll try to reproduce!

**Comment by eddynaka** [comment]
Hi @karianna,

below the versions:
Microsoft Edge
Version 89.0.774.77 (Official build) (64-bit)

Chrome
Version 89.0.4389.128 (Official Build) (64-bit)

Windows 10 Enterprise
Build 19042.928

**Comment by karianna** [comment]
@gdams Can you take a look and repro?

**Comment by eddynaka** [comment]
talked with @d3r3kk and we will try a call later to get more info. :)

**Comment by d3r3kk** [comment]
Confirmed.

Seems regional. When I connect from Sao Paulo, for instance, using a VPN connection, I get the same result.

I will bring this up with the team and we'll let you know when we sort it out! Thanks for bringing this to our attention @eddynaka! Very much appreciated.

**Comment by d3r3kk** [comment]
This is being reported as resolved now, it seems that there was a deployment of the headers over the past day. The team who owns that deployment has reported that they've since resolved the problem.

@eddynaka can you please look again now and let us know if things look proper yet?

**Comment by eddynaka** [comment]
@d3r3kk , its working fine! thank you :)
