### ISSUE TITLE
Minecolonies bug

### ISSUE THREAD

**Issue by CraftyPeat** [microsoft/openjdk#322]
**Describe the bug**

Sometimes when the build tool is used in creative to preview builds the game crashes suddenly

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]: (windows 10)

# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x129313e]

The output from `java --version`

**To Reproduce:**

1. grab build tool
2. right click
3. crash

**Expected behavior**

I expected to be placing a preview of a building for the minecolonies mod

**Screenshots, Logs etc**

https://gist.github.com/CraftyPeat/950ba69b38236abc654acebe7def7ac1

**Additional context**

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
