### ISSUE TITLE
provide GraalVM Distro, support native-image

### ISSUE THREAD

**Issue by shinestmt** [microsoft/openjdk#326]
**Describe the solution you'd like**
support native-image, as same as `Liberica Native Image Kit`  
BellSoft:   https://bell-sw.com/liberica-native-image-kit/

**Comment by karianna** [comment]
@shinestmt - We'd like to hear more about your use case.  Is this for a managed service that Azure provides or are you looking to bring Quarkus or Spring Native Boot or similar?
