### ISSUE TITLE
Minecraft keeps crashing when entering netherportal

### ISSUE THREAD

**Issue by erik-ehjwier** [microsoft/openjdk#336]
Everytime I try to go through a nether portal my game will crash for some reason. This crash apeared random cause I also played these mods with no problems. How do I fix this? I also have added one of the many error logs.
[hs_err_pid23044.log](https://github.com/microsoft/openjdk/files/9954584/hs_err_pid23044.log)

**Comment by itsTyrion** [comment]
nvidia driver issue, this also occurs when using a different Java distribution and MultiMC/PrismMC, so NVIDIA has to fix this. 
Go back one version or 2
