### ISSUE TITLE
Minecraft crashing every time I go through the nether portal

### ISSUE THREAD

**Issue by Lewisccf** [microsoft/openjdk#340]
**Describe the bug**
Minecraft crashes every time I enter or exit the nether through the portal. Only change was updating my 3080 gaming driver and Java.

**Desktop (please complete the following information):**
Windows 11

**MSFT Build of OpenJDK Version:**
Verison 8 Update 351 (build 1.8.0_351-b10)

**To Reproduce:**
Enter the nether... see black screen for half a second and minecraft just closes. Then reopen the minecraft launcher and the crash message appears.

**Screenshots, Logs etc**
![image](https://user-images.githubusercontent.com/118118055/201531469-53b868f7-da14-418f-9954-a2ceca7d7b75.png)

**Comment by itsTyrion** [comment]
nvidia driver issue, this also occurs when using a different Java distribution and MultiMC/PrismMC, so NVIDIA has to fix this. 
Or maybe Sodium. 
Go back one nvidia driver version or 2
