### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by AndreyQM** [microsoft/openjdk#341]
Game crashing with code 1

Windows 10, 19045.2251
OS & version [e.g. Windows 10, 1822]:

Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)

Every time i try opening the game it just crashes, with the exit code 1

![image](https://user-images.githubusercontent.com/118479939/202543372-0a3bee5f-e6c5-485e-a0f0-57449fee8eb7.png)

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
