### ISSUE TITLE
Game crashes when I enter new dimension

### ISSUE THREAD

**Issue by RandomHello** [microsoft/openjdk#343]
Game crashing with exit code 1

Windows 11 OS Build 22621.819

Microsoft-32931 (17.0.3+7-LTS)

Minecraft fatally crashes when entering another dimension/world

Enter other dimension or world, and spawn at set spawnpoint

![Screenshot (10)](https://user-images.githubusercontent.com/118569815/202802769-033f140b-6196-4c46-9515-663dbde40776.png)

**Comment by itsTyrion** [comment]
nvidia driver issue, this also occurs when using a different Java distribution and MultiMC/PrismMC, so NVIDIA has to fix this. 
Or maybe Sodium. 
Go back one nvidia driver version or 2

**Comment by RandomHello** [comment]
Thank you for helping me address this issue

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
