### ISSUE TITLE
MSI for ARM64 Java should install in C:\Program Files, not C:\Program Files (Arm)

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [microsoft/openjdk#344]
**Describe the bug**

The "c:\Program Files (Arm)" folder is for ARM32 binaries. To confirm this, run `c:\Windows\sysarm32\cmd.exe` on an ARM64 machine and look at the environment variables

```
PROCESSOR_ARCHITECTURE=ARM
ProgramFiles=C:\Program Files (Arm)
ProgramFiles(Arm)=C:\Program Files (Arm)
ProgramFiles(x86)=C:\Program Files (x86)
```

Whereas for ARM64 with `C:\Windows\system32\cmd.exe` they are

```
PROCESSOR_ARCHITECTURE=ARM64
ProgramFiles=C:\Program Files
ProgramFiles(Arm)=C:\Program Files (Arm)
ProgramFiles(x86)=C:\Program Files (x86)
```

**Desktop (please complete the following information):**

Microsoft Windows [Version 10.0.22621.819]

ARM64

Windows Dev Kit 2023

**MSFT Build of OpenJDK Version:**

```
C:\Program Files (Arm)\Microsoft\jdk-11.0.17.8-hotspot\bin>java --version
openjdk 11.0.17 2022-10-18 LTS
OpenJDK Runtime Environment Microsoft-6841889 (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-6841889 (build 11.0.17+8-LTS, mixed mode)
```

```
C:\Program Files (Arm)\Microsoft\jdk-17.0.5.8-hotspot\bin>java --version                    
openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Microsoft-6841604 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-6841604 (build 17.0.5+8-LTS, mixed mode)
```

**To Reproduce:**

Install ARM64 OpenJDK MSI on ARM64 system ( eg Windows Dev Kit 2023 )
Confirm directory it installs in.

**Expected behavior**

ARM64 binaries should be installed under "C:\Program Files"

**Comment by d3r3kk** [comment]
We should look into this closer. Perhaps the installer has hard-coded paths that aren't 100% correct for this arch. See [SHGetKnownFolderPath](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) for one way to determine this 100%, and our good friend from ["The Old New Thing" has even blogged about it!](https://devblogs.microsoft.com/oldnewthing/20220329-00/?p=106404).

**Comment by d3r3kk** [comment]
@gdams @karianna @brunoborges FYI

**Comment by gdams** [comment]
Yeah, this seems correct from some quick reading. I'll prepare a patch at Adoptium and then it can be pulled down @d3r3kk

**Comment by karianna** [comment]
@gdams Has the patch landed upstream?

**Comment by rhubarb-geek-nz** [comment]
Neither  microsoft-jdk-11.0.18-windows-aarch64.msi or microsoft-jdk-17.0.6-windows-aarch64.msi appear to have the fix. They both say "Program Files (Arm)".

**Comment by rhubarb-geek-nz** [comment]
```
 Directory of C:\Program Files (Arm)\Microsoft

26/01/2023  07:52 pm    <DIR>          .
19/11/2022  12:40 am    <DIR>          ..
26/01/2023  07:52 pm    <DIR>          jdk-11.0.18.10-hotspot
26/01/2023  07:52 pm    <DIR>          jdk-17.0.6.10-hotspot
```

**Comment by karianna** [comment]
ACK - we still have to apply the fix.  Will let you know if we re-spin this particular version

**Comment by brunoborges** [comment]
@joe-braley @Luigi96 has this been fixed?

**Comment by d3r3kk** [comment]
@brunoborges no not yet. We have some work to do to be able to consume Adoptium's installer code properly, and we have some work to do regarding upgrading Wix and fixing some Accessibility problems too. I was hoping to get to all of that before March 31st.

**Comment by rhubarb-geek-nz** [comment]
Good news

```
C:\Program Files\Microsoft>dir
 Volume in drive C is Local Disk
 Volume Serial Number is ACF6-E72D

 Directory of C:\Program Files\Microsoft

02/05/2024  07:28    <DIR>          .
02/05/2024  07:27    <DIR>          ..
02/05/2024  07:28    <DIR>          jdk-11.0.23.9-hotspot
02/05/2024  07:27    <DIR>          jdk-17.0.11.9-hotspot
02/05/2024  07:27    <DIR>          jdk-21.0.3.9-hotspot
               0 File(s)              0 bytes
               5 Dir(s)  317,487,587,328 bytes free

```
And 

```
C:\Program Files\Microsoft Visual Studio\2022\Community>dumpbin /headers "C:\Program Files\Microsoft\jdk-11.0.23.9-hotspot\bin\java.exe" | findstr " machine "
            AA64 machine (ARM64)

C:\Program Files\Microsoft Visual Studio\2022\Community>dumpbin /headers "C:\Program Files\Microsoft\jdk-17.0.11.9-hotspot\bin\java.exe" | findstr " machine "
            AA64 machine (ARM64)

C:\Program Files\Microsoft Visual Studio\2022\Community>dumpbin /headers "C:\Program Files\Microsoft\jdk-21.0.3.9-hotspot\bin\java.exe" | findstr " machine "
            AA64 machine (ARM64)

```
