### ISSUE TITLE
Minecraft fabric-loader 0.4.10 crash

### ISSUE THREAD

**Issue by 1QNIK** [microsoft/openjdk#347]
When I'm playing fabric minecraft sometimes while I'm playing on some servers/singleplayer it just crashes in random moments

Windows 10 Version 22H2 x64

Crash Report:
[hs_err_pid31672.log](https://github.com/microsoft/openjdk/files/10079421/hs_err_pid31672.log)

It keeps crashing including deleting some mods too

**Comment by itsTyrion** [comment]
nvidia driver issue, this also occurs when using a different Java distribution and MultiMC/PrismMC, so NVIDIA has to fix this. 
Go back one version
