### ISSUE TITLE
Native code fatal error. Render thread.

### ISSUE THREAD

**Issue by Kotofey008** [microsoft/openjdk#348]
**Bug:**
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe31342d20, pid=8532, tid=9924

**Desktop:**
OS & version: Windows 10 22H2 (19045.2251)

**MSFT Build of OpenJDK Version:**
Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)

**Problematic frame:**
C  [nvoglv64.dll+0x1852d20]

**Additional context**
Crashing when rendering settings changing.

**Crash report:**
[hs_err_pid17428.log](https://github.com/microsoft/openjdk/files/10096282/hs_err_pid17428.log)

**Comment by itsTyrion** [comment]
It is GPU driver related. Go back one or 2 versions.

**Comment by KyKirma** [comment]
same
