### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by taddmencer** [microsoft/openjdk#349]
Playing Minecraft recently, and when I try to go into the Nether, or really anything changing environments or even loading ... the game would crash. 

Happened three times during a live stream. 

This is the error:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb34512d20, pid=391028, tid=391132
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x1852d20]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Dos.name=Windows 10 -Dos.version=10.0 -Xss1M -Djava.library.path=C:\Users\Tadd\Documents\Curse\Minecraft\Install\bin\b4052d67519fb556e5e527a2b96496eb479d5de2 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.3.508 -DFabricMcEmu= net.minecraft.client.main.Main  -Xmx4000m -Xms256m -Dminecraft.applet.TargetDirectory=C:\Users\Tadd\Documents\Curse\Minecraft\Instances\Fabulously Optimized (3) -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dlog4j.configurationFile=C:\Users\Tadd\Documents\Curse\Minecraft\Install\assets\log_configs\client-1.12.xml net.fabricmc.loader.impl.launch.knot.KnotClient --username LordThaddius --version fabric-loader-0.14.10-1.19.2 --gameDir C:\Users\Tadd\Documents\Curse\Minecraft\Instances\Fabulously Optimized (3) --assetsDir C:\Users\Tadd\Documents\Curse\Minecraft\Install\assets --assetIndex 1.19 --uuid 7d8e1ddb50d14a17863d2ab3ff593463 -Hm6M --clientId YTFjN2U4MzktYTQzZi00MzZhLWI5ODItNTZhNjM3MWIxYzI0 --xuid 2535421901502084 --userType msa --versionType release

Host: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 8 cores, 23G,  Windows 10 , 64 bit Build 19041 (10.0.19041.2251)
Time: Mon Nov 28 22:45:33 2022 Eastern Standard Time elapsed time: 6802.130751 seconds (0d 1h 53m 22s)

**Comment by taddmencer** [comment]
There is a load of extra stuff, but Github says it is too much, and then spat in my left eye, which really burns.

**Comment by itsTyrion** [comment]
![image](https://user-images.githubusercontent.com/17730120/204917333-57e43a29-7de2-434c-b98a-230669698e5e.png)
NVOGLv64 = **NV**IDIA **O**pen**GL** **v**ersion**64**bit, OpenGL being the graphics API that minecraft uses. 
So the crash is related to GPU drivers. 
Are you using the latest NVIDIA driver?

**Comment by Quaderxy** [comment]
I have a similar error on the Fabric version, I tried to fix it by changing the java version to an older and up-to-date one, it didn't help, I also put older drivers on the video card, crashes with the litematica mod, I don't know what's the matter, maybe you need to wait for a fix from the developers

**Comment by itsTyrion** [comment]
how far did you go back with the GPU drivers?

**Comment by taddmencer** [comment]
Ok so, I think I got it figured out. 

I use a Modpack called Fabulously Optimized. Apparently, the shader mod, Iris Shaders, had conflicts. But simply updating them didn't fix the issue. I had to recreate the whole modpack profile.

I'm not 100% sure if the issue was because of nvidia drivers butting heads with something in the Iris mod. But so far, this is working for me.

**Comment by jurohn** [comment]
> I have a similar error on the Fabric version, I tried to fix it by changing the java version to an older and up-to-date one, it didn't help, I also put older drivers on the video card, crashes with the litematica mod, I don't know what's the matter, maybe you need to wait for a fix from the developers

---------------
Same issue here with litematica. Thank you a lot for figuring that out. 
After hours of googling i found your reply!

**Comment by itsTyrion** [comment]
great. litematica also has a habit of triggering anticheats with EasyBuild (wrong packet order), GitHub issue has been open for a year with no apparent changes

**Comment by denbeck** [comment]
https://github.com/taddmencer   
Did you ever get your problem fixed with Minecraft and the Java Runtime Environment #349 ?  I am having the same issue and can't find a solution.

**Comment by taddmencer** [comment]
> https://github.com/taddmencer Did you ever get your problem fixed with Minecraft and the Java Runtime Environment #349 ? I am having the same issue and can't find a solution.

Yes and no. The problem was incompatibility with an NVidia update and the Minecraft shader addon, Indium. Eventually, an updated version of Indium resolved the issue.

**Comment by denbeck** [comment]
Thanks for the help 


Sent from the all new AOL app for iOS


On Monday, July 10, 2023, 5:24 AM, Tadd Mencer ***@***.***> wrote:





https://github.com/taddmencer Did you ever get your problem fixed with Minecraft and the Java Runtime Environment #349 ? I am having the same issue and can't find a solution.


Yes and no. The problem was incompatibility with an NVidia update and the Minecraft shader addon, Indium. Eventually, an updated version of Indium resolved the issue.
