### ISSUE TITLE
Minecraft Java Edition launcher crashes with Exit code: 1 stating 'The crash happened outside the Java Virtual Machine in native code. See problematic frame for where to report the bug.'

### ISSUE THREAD

**Issue by astemkar** [microsoft/openjdk#371]
(Upon contacting the Minecraft support, I was told to raise a query here on Github.)

When I launch Minecraft Java Edition through the official launcher, the game crashes with an Exit code: 1, and the game output window states that 'The crash happened outside the Java Virtual Machine in native code. See problematic frame for where to report the bug.'

OS:Windows 10, Version: Build 19045

The output from `java --version`: 
java 17.0.2 2022-01-18 LTS 
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)

N.A. since it takes place in the game window

Expected behavior: Expected the game to launch after starting it.

Screenshot of Game output window:
![Screenshot 2022-12-30 125215](https://user-images.githubusercontent.com/48828202/210044985-f756708d-7e2b-4742-9e0b-d209e7d6a246.png)

Please let me know in case any more details are required from my side.

**Comment by karianna** [comment]
@astemkar Are you able to post the contents of the `hs_err_pid<number>.log error log file?

**Comment by dan-uwaifo** [comment]
i have the same issue and i have logs

**Comment by dan-uwaifo** [comment]
[hs_err_pid2200.log](https://github.com/microsoft/openjdk/files/10339741/hs_err_pid2200.log)

**Comment by karianna** [comment]
@astemkar - FYI - I also notice that your `java --version` command outputs `17.0.2+8` but that Minecraft is actually running the bundled `17.0.3+7`.

For both @astemkar and @dan-uwaifo 

Are you able to try installing 17.0.5 from https://learn.microsoft.com/en-gb/java/openjdk/download and then:

1. Open Minecraft JE
2. Go to Installations
3. For the _Latest Release_ installation select the _..._ button on the RH side and select _Edit_
4. Click on the _More Options Dropdown_
5. Click on the _Browse_ link in the _Java Executable_ field and navigate to the _javaw.exe_ file in the directory that you just installed 17.0.5 to.
6. Restart Minecraft JE and see if that resolves the issue, if not please do post a new hs_err_pid_<number> file here

**Comment by dan-uwaifo** [comment]
Ah well I would to that but I managed to fix everything due to a driver update. Thought it was updated since it was relatively new but checked the drivers via amd and now everything's working

**Comment by RustyBot572** [comment]
How did you update your drivers?

**Comment by MinikatzeM** [comment]
[hs_err_pid18184.log](https://github.com/microsoft/openjdk/files/10355977/hs_err_pid18184.log)

I followed the tutorial from karianna but it didn't work

**Comment by karianna** [comment]
@MinikatzeM You may be impacted by the NVidia driver bug (please update to latest) or the AMD driver workaround.  See https://github.com/LWJGL/lwjgl3/issues/836#issuecomment-1362899189

**Comment by RustyBot572** [comment]
@karianna what do we do exactly? I see the comment but i don't know what you want us to do to fix the problem.

**Comment by brunoborges** [comment]
@RustyBot572 best thing to do here is talk with the folks from the LWJGL project.
