### ISSUE TITLE
When I enter a nether portal or press an specific key on my keyboard the game crashes

### ISSUE THREAD

**Issue by OctoBoiii** [microsoft/openjdk#372]
**Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by karianna** [comment]
This report seems to be empty.
