### ISSUE TITLE
Playing on a modded server i own and it keeps crashing everytime i open it. 

### ISSUE THREAD

**Issue by panzers973** [microsoft/openjdk#377]
Whenever I open the server im good for like a good 15 seconds then it just crashes i have no idea what the issue is but i have tried what feels like everything allocated more ram deleted all files and redownloaded them etc. would love it if i could get some more heads on this issue 
**Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are using a modified version of Minecraft. The following was detected in your crash report:

Please report this crash to the mod creator. If you can also reproduce this crash without having any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
