### ISSUE TITLE
Publish DEB for Ubuntu 22.04

### ISSUE THREAD

**Issue by brunoborges** [microsoft/openjdk#388]
As per #262.

- [x] Publish DEB package for Ubuntu 22.04 on ` packages.microsoft.com`  - @d3r3kk 
- [ ] Update [documentation](https://learn.microsoft.com/en-us/java/openjdk/install#install-on-ubuntu) - @brunoborges

**Comment by d3r3kk** [comment]
Closed as of July-2023-PSU release.
