### ISSUE TITLE
optifine crash

### ISSUE THREAD

**Issue by whyareyourunningustupid** [microsoft/openjdk#428]
**Describe the bug**
optifine 1.19.2 crashes when loading into  a world

**Desktop (please complete the following information):**

OS & version [e.g. Windows 11, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

1. start up optifine 1.19.2 in mc launcher
2. Click on single player
3. pick a world

**Expected behavior**
to load in to the world

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**
It also happen with other versions of optifine only use mc java client and I do have curseforge

**Comment by karianna** [comment]
Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
