### ISSUE TITLE
Game crashes since updating to 9.0.1

### ISSUE THREAD

**Issue by Sean860** [microsoft/openjdk#436]
**Describe the bug**
Since I updated to version 9.0.1 when entering the portal for the vault the game freezes then either takes a very long time to start or the game crashes. When I do get into the vault it laggy and randomy crashes with a out of memory error.

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

Windows 11

**MSFT Build of OpenJDK Version:**

The output from `java --version`

1.18.2

**To Reproduce:**

1. Try to enter vault
2. If game doesn't crash play till crash.

**Expected behavior**

Game shouldn't crash

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

![image](https://user-images.githubusercontent.com/132258036/235435731-81420a7d-874e-4c46-941e-7181854ed5c0.png)

**Additional context**

No but except for the crashing I'm loving the new update.

**Comment by Sean860** [comment]
Never mind. Think I found the issue. The allocated memory in Curseforge reset after the update. I turned it back to 8192 and seems to be fine now. Sorry

**Comment by Rubin1111** [comment]
I did recently updated to _0.1.8.9a and since then, every time I try to launch, I recieve an Exit-Code 1 with this crash-report attached:
[hs_err_pid10304.log](https://github.com/microsoft/openjdk/files/11364979/hs_err_pid10304.log)
I suppose there is a problem with the runtime.
OS: Win 10 64 bit
Mc Version: 1.19.4

**Comment by brunoborges** [comment]
Curseforge is a mod. Please refer to their forum.
