### ISSUE TITLE
Minecraft Loading Issue

### ISSUE THREAD

**Issue by elance02** [microsoft/openjdk#44]
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006227c153, pid=8460, tid=7940
#
# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x14c153]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by karianna** [comment]
@elance02 - Thanks for posting this to us! Are you able to tell us:

* Which version of Minecraft you're using
* Do you have any Minecraft Mods installed?
* Which exact version of Windows are you using?
* Does this crash repeatedly happen or only on occasion?

**Comment by rednnnno** [comment]
Just wanted to mention I was looking for JDK for Minecraft and after seeing this post figured I would try it. It seems to work fine for me with `minecraft server version 1.16.5`.
Command line options:
`javaw.exe -Xms512M -Xmx4G -XX:SoftMaxHeapSize=1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:G1HeapRegionSize=32M -Xbatch -jar server.jar`
