### ISSUE TITLE
Missing FeatureOracleJavaSoft feature in Microsoft OpenJDK Windows install

### ISSUE THREAD

**Issue by apique13** [microsoft/openjdk#475]
**Describe the bug**
Hi, the documented FeatureOracleJavaSoft is missing in Microsoft OpenJDK installs.
Still true in 17.0.7 and 11.0.19 downloaded from https://learn.microsoft.com/en-us/java/openjdk/download

**Desktop (please complete the following information):**

Windows 10, 1822

**MSFT Build of OpenJDK Version:**

17.0.7 and 11.0.19 (and all versions before too)

**To Reproduce:**

Install Microsoft OpenJDK, the feature to permits installing JavaSoft registrey key is not available.
I checked it with an MSI Editor and the Feature is not present in the msi file.
The feature is documented on the page :
https://learn.microsoft.com/en-us/java/openjdk/install
FeatureOracleJavaSoft | Updates registry keys HKLM\SOFTWARE\JavaSoft\.

**Expected behavior**

A feature which install the JavaSoft registry key used by a lot of application to find the current Java install.
This feature is present in Adoptium's jdk, Zulu's JDK and much more.

**Screenshots, Logs etc**
![Capture](https://github.com/microsoft/openjdk/assets/52655063/77f8eea2-914d-4446-8491-5f96c107cec5)

**Additional context**

**Comment by apique13** [comment]
Here a screenshot of registry keys in the msi compared to others JDK :
![msi_compare](https://github.com/microsoft/openjdk/assets/52655063/23ccf17c-981c-45c5-92cc-983e7c36b9cd)
The fetures available in Microsoft JDK :
![features](https://github.com/microsoft/openjdk/assets/52655063/bf26e035-4767-4ca5-b7a8-89b3866972bf)

**Comment by karianna** [comment]
A customer was recently able to install this with 17.0.8 but it is still worth checking our latest installers and installers - 1

**Comment by GeoSimos** [comment]
The issue is also present in 21.x version installers.

**Comment by brunoborges** [comment]
Thanks @GeoSimos. Out of curiosity, why is this flag important to you?

**Comment by GeoSimos** [comment]
Hi @brunoborges,
I replied here https://github.com/microsoft/openjdk/discussions/295#discussioncomment-8628804.

**Comment by brunoborges** [comment]
@jmjaffe37 let's review if we need this feature at all.

If I recall correctly, this feature comes from the old days of JREs and integration with browsers.

**Comment by GeoSimos** [comment]
> @jmjaffe37 let's review if we need this feature at all.
> 
> If I recall correctly, this feature comes from the old days of JREs and integration with browsers.

If you can provide a way for us to detect the installed Java version and architecture, then it may not be required, however, lots of solutions are using those Registry keys to do several stuff.

**Comment by brunoborges** [comment]
Do you have some examples of tools that rely on this registry key to identify presence of Java installed?

**Comment by brunoborges** [comment]
@GeoSimos let me know if you still need this.

**Comment by GeoSimos** [comment]
> [@GeoSimos](https://github.com/GeoSimos) let me know if you still need this.

Hi @brunoborges,


Yes I do, please add it in your planned features.

**Comment by brunoborges** [comment]
@GeoSimos can you provide details about why you need this?

**Comment by GeoSimos** [comment]
@brunoborges please see previous messages above, I have already provided explanations.
