### ISSUE TITLE
Crash when trying to load a modpack.

### ISSUE THREAD

**Issue by Aganthor** [microsoft/openjdk#477]
**Describe the bug**
I get a SIGSEGV error when starting a fabric modpack (Another Quality Modpack 2).

**Desktop (please complete the following information):**

Garuda Linux kernel 6.3.8-zen1-1-zen, Plasma 5.27.5
Using ATLauncher version 3.4.28.1

**MSFT Build of OpenJDK Version:**

The output from `java --version` :
`openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)`

**To Reproduce:**

1. Install mod pack (version 1.5.9)
2. Here are the JVM arguments: `-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`
3. launch

**Expected behavior**
The modpack should run fine. If I launch the modpack All of Fabric 6, everything is fine.

**Screenshots, Logs etc**
Here is a link to the crash report: [crash report.](https://bin.garudalinux.org/?5982be13eada7df0#DmePCJUprEVYYuq7SvPXxB82HE5kTdZcR32CgZPFqf26)

**Comment by Joe112206** [comment]
yes i am having the same problem

**Comment by brunoborges** [comment]
Please contact the mod developer. We do not support modded Minecrafts.
