### ISSUE TITLE
Exception access violation error

### ISSUE THREAD

**Issue by doggednamed1** [microsoft/openjdk#491]
**Describe the bug**
I have never encountered a bug like this before, and im worried that something may have broke. I'll paste the error log.
[hs_err_pid7032.log](https://github.com/microsoft/openjdk/files/11898692/hs_err_pid7032.log)

**Comment by doggednamed1** [comment]
i think curseforge uses the old mc launcher.

**Comment by karianna** [comment]
@doggednamed1 Rest of the advice will still hold true.
