### ISSUE TITLE
Provide IA-32 (aka i386, i686, x86) builds for Windows and *nix

### ISSUE THREAD

**Issue by KOLANICH** [microsoft/openjdk#50]
**Is your feature request related to a problem? Please describe.**
32-bit Windows systems are still widely used. They are beneficial for systems with low amount of RAM.
It is well-known that

* it is possible to build OpenJDK for such systems;
* Linux distros supporting 32-bit CPUs usually provide 32-bit packages for OpenJDK in their repos;
* there are some OpenJDK for 32-bit Windows, though there are not as many of them as for 64-bit Windows;
* the decision to drop 32-bit support was a political decision made by Oracle. They even have published 32-bit builds for Windows, then removed them, and then required everyone distributing copies of them to stop doing that under a threat od DMCA.

**Describe the solution you'd like**
I want MS to distribute prebuilt 32-bit builds.

**Describe alternatives you've considered**
The alternative is using the 32-bit builds of OpenJDK distributed by other companies. But it is a bad one because
* I have never heard about those companies before I have encountered their OpenJDK builds. I don't trust them enough.
* If those companies stopped distributing builds, users would have to build 32-bit builds themselves. It is not good.

**Comment by karianna** [comment]
@KOLANICH Thanks for the feedback! At this stage we will not be providing Win 32 MSST builds of OpenJDK.  However, we are a Strategic Member of Eclipse Adoptium (currently adoptopenjdk.net, but migrating across) and you can get Windows 32 builds from there, e.g. https://adoptopenjdk.net/releases.html.
