### ISSUE TITLE
msopenjdk-11_11.0.20-1_amd64.deb contains a cacert symlink pointing to a non-existing location

### ISSUE THREAD

**Issue by rutgerputter** [microsoft/openjdk#515]
**Describe the issue**
The ms-openjdk-11 package contains a symlink in /lib/security/cacerts to a non-existing location to /etc/ssl/certs/adoptium/cacerts.
We've downloaded it from https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msopenjdk-11/ and we've only tested on Debian 12, but it could be happening in more versions.

This causes any use of the trust store in cacerts to break.

**When did the issue occur?**
It happened when upgrading from msopenjdk-11_11.0.19-1 to msopenjdk-11_11.0.20-1.
msopenjdk-11_11.0.19-1 Contains it's own cacerts file and does not use a symlink.

If applicable, what package did you attempt to install, and from which repo?
See above.

We've temporarily pinned our version to msopenjdk-11_11.0.19-1 until this is fixed.

This issue has also been raised at https://github.com/microsoft/linux-package-repositories/issues/68, but we've been sent here to report.

**Comment by nsballmann** [comment]
Just for reference https://github.com/microsoft/linux-package-repositories/issues/68#issuecomment-1645314623: 
> ```
> vagrant@bookworm:~$ apt-cache policy msopenjdk-11
> msopenjdk-11:
>   Installed: 11.0.20-1
>   Candidate: 11.0.20-1
>   Version table:
>  *** 11.0.20-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>         100 /var/lib/dpkg/status
>      11.0.19-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.18-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.17-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.16-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.15+10-LTS-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
> vagrant@bookworm:~$ dpkg -L msopenjdk-11 | grep cacerts
> /usr/lib/jvm/msopenjdk-11-amd64/lib/security/cacerts
> vagrant@bookworm:~$ ls -lah /usr/lib/jvm/msopenjdk-11-amd64/lib/security/cacerts
> lrwxrwxrwx 1 root root 31 Jul 19 22:19 /usr/lib/jvm/msopenjdk-11-amd64/lib/security/cacerts -> /etc/ssl/certs/adoptium/cacerts
> vagrant@bookworm:~$ ls -lah /etc/ssl/certs/adoptium/cacerts
> ls: cannot access '/etc/ssl/certs/adoptium/cacerts': No such file or directory
> ```

**Comment by nsballmann** [comment]
And https://github.com/microsoft/linux-package-repositories/issues/68#issuecomment-1645326513:

> Quickly confirmed in an `ubuntu:jammy` container:
> 
> ```
> root@5d89d70bc5d6:~# cat /etc/os-release 
> PRETTY_NAME="Ubuntu 22.04.2 LTS"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.2 LTS (Jammy Jellyfish)"
> VERSION_CODENAME=jammy
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> UBUNTU_CODENAME=jammy
> root@5d89d70bc5d6:~# apt-cache policy msopenjdk-11
> msopenjdk-11:
>   Installed: 11.0.20-1
>   Candidate: 11.0.20-1
>   Version table:
>  *** 11.0.20-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>         100 /var/lib/dpkg/status
>      11.0.19-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.18-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.17-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.16-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
>      11.0.15+10-LTS-1 500
>         500 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages
> root@5d89d70bc5d6:~# dpkg -L msopenjdk-11 | grep cacerts
> /usr/lib/jvm/msopenjdk-11-amd64/lib/security/cacerts
> root@5d89d70bc5d6:~# ls -lah /usr/lib/jvm/msopenjdk-11-amd64/lib/security/cacerts
> lrwxrwxrwx 1 root root 31 Jul 19 22:19 /usr/lib/jvm/msopenjdk-11-amd64/lib/security/cacerts -> /etc/ssl/certs/adoptium/cacerts
> root@5d89d70bc5d6:~# ls -lah /etc/ssl/certs/adoptium/cacerts
> ls: cannot access '/etc/ssl/certs/adoptium/cacerts': No such file or directory
> root@5d89d70bc5d6:~#
> ```

**Comment by karianna** [comment]
@rutgerputter & @nsballmann Hi folks, we uploaded the wrong package in error and this has now been replaced with a package which links to the std ca certificates.  Please do grab a fresh package and let us know if that resolves it for you!

**Comment by daviddavis** [comment]
@karianna did you build a new package with the same version? If so I will need to remove the old version from the cache.

**Comment by karianna** [comment]
> @karianna did you build a new package with the same version? If so I will need to remove the old version from the cache. 

Hi David, yes we did use the same version number AFAIK.  Apologies once more for the breakage!  Lessons were certainly learned.

**Comment by daviddavis** [comment]
No worries. I checked the links below and it looks like the new versions of the packages are being served so I think everything is good to go.

https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_amd64.deb
https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_arm64.deb
https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_amd64.deb
https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_arm64.deb
https://packages.microsoft.com/debian/10/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_amd64.deb
https://packages.microsoft.com/debian/10/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_arm64.deb

In the future, I recommend incrementing the version in situations like this if possible.

**Comment by karianna** [comment]
> No worries. I checked the links below and it looks like the new versions of the packages are being served so I think everything is good to go.
> 
> https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_amd64.deb https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_arm64.deb https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_amd64.deb https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_arm64.deb https://packages.microsoft.com/debian/10/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_amd64.deb https://packages.microsoft.com/debian/10/prod/pool/main/m/msopenjdk-11/msopenjdk-11_11.0.20-1_arm64.deb
> 
> In the future, I recommend incrementing the version in situations like this if possible.

Yep agreed, we've got that covered in our retro, the .2 should have been applied.  CC @d3r3kk

**Comment by Artuto** [comment]
Hi. I believe this issue is also present in OpenJDK 17 builds:

`org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/msopenjdk-17-arm64/lib/security/cacerts (No such file or directory)`

`lrwxrwxrwx 1 root root 31 Jul 19 22:13 /usr/lib/jvm/msopenjdk-17-arm64/lib/security/cacerts -> /etc/ssl/certs/adoptium/cacerts`

```
artuto@craftium:~$ sudo apt install msopenjdk-17
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
msopenjdk-17 is already the newest version (17.0.8-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

Debian 11

**Comment by karianna** [comment]
@Artuto Can you pull a fresh package (clear out any local cache you may have) - it should be corrected but if not we'd love to make sure!

**Comment by nsballmann** [comment]
Just for future reference about the Debian package version conventions: <https://www.debian.org/doc/debian-policy/ch-controlfields.html#version>

**Comment by karianna** [comment]
Will resolve alongside [17 issue reported ](https://github.com/microsoft/openjdk-docker/issues/74)

**Comment by karianna** [comment]
Update on this. We are currently testing a fix and we've added the extra version number so package managers should upgrade naturally from the broken package. Given we got this wrong the first time we'll be spending extra in our QA steps!

**Comment by rutgerputter** [comment]
It seems that the updated packages uploaded to packages.microsoft.com yesterday evening at 9PM CET. I've looked at the amd64 22.04 package and it now contains the correct cacerts file. Also, thanks for using the correct versioning :smile: .

**Comment by karianna** [comment]
@rutgerputter / all - yes you found it before we even updated this ticket, but 11, 17 packages are fixed and the container images have also been updated
