### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) when using Quilt launcher for Minecraft

### ISSUE THREAD

**Issue by shmelfa** [microsoft/openjdk#536]
No matter what i do, im getting this error when using the Quilt launcher for minecraft and trying to play on the Mythical Pixelmon mod pack in the Technic Launcher. I have tried literally everything and nothing has worked. Please advise. 

[hs_err_pid12952.log](https://github.com/microsoft/openjdk/files/12330045/hs_err_pid12952.log)

**Comment by shmelfa** [comment]
[MC-264830]

**Comment by karianna** [comment]
https://bugs.mojang.com/browse/MC-264830 was closed due to the bug report not being based on the latest version of Minecraft. Recommend talking to the launcher owners.
