### ISSUE TITLE
Minecraft crashes randomly

### ISSUE THREAD

**Issue by Crucciolo** [microsoft/openjdk#55]
**Describe the bug**
My minecraft crashed

**To Reproduce**
it randomly crash
**Expected behavior**
nothing

**Screenshots**
If applicable, add screenshots to help explain your problem.![image](https://user-images.githubusercontent.com/85629298/121369553-3e936580-c93c-11eb-859c-9e78d27c92b9.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [windows 10]

**Smartphone (please complete the following information):**

**Additional context**

Command Line: -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Dos.name=Windows 10 -Dos.version=10.0 -Xss1M -Djava.library.path=C:\Users\\AppData\Roaming\.minecraft\bin\3e09-4f06-3c5b-6bb2 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.2.3106 -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dlog4j.configurationFile=C:\Users\...
\AppData\Roaming\.minecraft\assets\log_configs\client-1.12.xml net.minecraft.client.main.Main --username Crucciolo --version 1.17 --gameDir C:\Users\feder\AppData\Roaming\.minecraft --assetsDir C:\Users\...\AppData\Roaming\.minecraft\assets --assetIndex 1.17 --uuid adb20268ac9e4f768d98f23edba4d90f --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMmM2MjZlY2EwYmMxNjc0YWQ1ZWVjZDQyMjgwMWY0NCIsInlnZ3QiOiJkMTY4ZWE2NTFjZjQ0ODE2OWRlM2VhNDliZmQwM2I5OCIsInNwciI6ImFkYjIwMjY4YWM5ZTRmNzY4ZDk4ZjIzZWRiYTRkOTBmIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MjM0MTkzODAsImlhdCI6MTYyMzI0NjU4MH0.uj8NsCDGprdJOc-a1WhwA0p0ykpD2CGcqLofWw0ReA0 --userType mojang --versionType release

Host: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz, 16 cores, 31G,  Windows 10 , 64 bit Build 19041 (10.0.19041.928)
Time: Wed Jun  9 16:00:17 2021 W. Europe Summer Time elapsed time: 628.713699 seconds (0d 0h 10m 28s)

---------------  T H R E A D  ---------------

Current thread (0x000001eaaefcecc0):  ConcurrentGCThread "G1 Conc#1" [stack: 0x0000000a9e600000,0x0000000a9e700000] [id=16532]

Stack: [0x0000000a9e600000,0x0000000a9e700000],  sp=0x0000000a9e6ff338,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0xcd36]

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000000000088890

Register to memory mapping:

RIP=0x00007ffa3576cd36 jvm.dll
RAX=0x0 is NULL
RBX=0x000001ea8dfd3a01 points into unknown readable memory: 10 d9 8d ea 01 00 00
RCX=
[error occurred during error reporting (printing register info), id 0xc0000005, EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa35dd12f3]

**Comment by karianna** [comment]
Discussing with the Minecraft Team.

**Comment by karianna** [comment]
@Crucciolo - Are you able to submit this issue over at https://bugs.mojang.com/projects/MC/issues/ - the Mojang folks will take the first pass at Triage :-)

**Comment by karianna** [comment]
@Crucciolo - Any luck submitting the issue at Mojang?

**Comment by apple502j** [comment]
@karianna There are a lot of reports that Minecraft segfaults on Mojang bugtracker. I still don't know how Minecraft, a Java program, can segfault - it may be LWJGL, it may be OpenJDK bug, it may be Minecraft bug, I am unsure. See also this link for MC bug reports indicating segfault:

https://bugs.mojang.com/browse/MC-229295?jql=project%20%3D%20MC%20AND%20issuetype%20%3D%20Bug%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22access%20violation%22%20ORDER%20BY%20created%20DESC%2C%20cf%5B10701%5D%20DESC%2C%20updated%20DESC

**Comment by karianna** [comment]
> @karianna There are a lot of reports that Minecraft segfaults on Mojang bugtracker. I still don't know how Minecraft, a Java program, can segfault - it may be LWJGL, it may be OpenJDK bug, it may be Minecraft bug, I am unsure. See also this link for MC bug reports indicating segfault:
> 
> https://bugs.mojang.com/browse/MC-229295?jql=project%20%3D%20MC%20AND%20issuetype%20%3D%20Bug%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22access%20violation%22%20ORDER%20BY%20created%20DESC%2C%20cf%5B10701%5D%20DESC%2C%20updated%20DESC

@apple502j - Thank you - we've seen the uptick with the support cases here and at Mojang (lwjgl itself may not be the culprit, but the graphics drivers it calls - we're digging in regardless) and together we're digging in to investigate!  As you can imagine with _this_ many players, there are a lot of unique configurations that are challenging for us to reproduce, but this is part of the technical challenge/fun that we love and we're very determined to get folks back on their feet with no crashes (my 6-year-old would expect nothing less ;-)).

Appreciate everyone's patience here, I know my own personal reaction to not be able to play my world due to a crash would be one of frustration!

**Comment by apple502j** [comment]
Okay, so here are the things:

- MC-229049: nullptr deref write in LWJGL? Not OpenJDK probably
- MC-229121: DEP violation in non-null address while loading LWJGL binary?
- MC-229195: nullptr deref write in ntdll.dll, a Windows component, called from LWJGL.
- MC-229295: **This may be OpenJDK bug** - invalid pointer read, does not indicate LWJGL

**Comment by Marcono1234** [comment]
> * MC-229295: **This may be OpenJDK bug** - invalid pointer read, does not indicate LWJGL

Maybe related to https://github.com/microsoft/openjdk/issues/63#issuecomment-869844927?
On their Mojang bug report the reporter attached multiple JVM crash reports, each at different locations:
- `J 1414 c2 java.util.HashMap.get(Ljava/lang/Object;)Ljava/lang/Object; java.base@16.0.1 (19 bytes) @ 0x000001ec1725203e [0x000001ec17251f20+0x000000000000011e]`
- `j  sun.nio.fs.WindowsPathParser.normalize(Ljava/lang/StringBuilder;Ljava/lang/String;I)Ljava/lang/String;+25 java.base@16.0.1`
- `V  [jvm.dll+0x367f46]`
- `j  com.mojang.datafixers.functions.PointFreeRule$CompRewrite.rewrite(Lcom/mojang/datafixers/types/Type;Lcom/mojang/datafixers/functions/PointFree;)Ljava/util/Optional;+0`

So maybe something was corrupting the process memory for them?
