### ISSUE TITLE
Bug - Automatic location resolver is incorrect for SHA256 file

### ISSUE THREAD

**Issue by samruddhikhandale** [microsoft/openjdk#563]
**Describe the bug**

If one downloads `https://aka.ms/download-jdk/microsoft-jdk-11-linux-x64.tar.gz`, then the http URL is automatically converted to `https://aka.ms/download-jdk/microsoft-jdk-11.0.20.1-linux-x64.tar.gz`. See 👇  (This works as expected)

![Image](https://github.com/microsoft/openjdk/assets/24955913/f05d1496-4046-4842-a2d9-ffdc5a34cff4)
![Image](https://github.com/microsoft/openjdk/assets/24955913/5a8d51de-60c0-438d-bca7-6ddb3f1b790d)

However, the URL conversion for SHA256 checksum file doesn't seem to be working fine since a couple of days

![Image](https://github.com/microsoft/openjdk/assets/24955913/bbf858e4-c7a5-4bcb-92d0-5008a9d37264)
![Image](https://github.com/microsoft/openjdk/assets/24955913/ad37d1ac-3bfc-470a-bae1-e77bdfb03e67)

**Current behavior** -`https://aka.ms/download-jdk/microsoft-jdk-11-linux-x64.tar.gz.sha256sum.txt` is redirected to `https://aka.ms/download-jdk/microsoft-jdk-11.0.20-linux-x64.tar.gz.sha256sum.txt`

**Expected behavior** - `https://aka.ms/download-jdk/microsoft-jdk-11-linux-x64.tar.gz.sha256sum.txt` must be redirected to `https://aka.ms/download-jdk/microsoft-jdk-11.0.20.1-linux-x64.tar.gz.sha256sum.txt`

Notice the missing `.1`  in the version field. 

Note: This happens for v17 and v8 as well.

**Comment by karianna** [comment]
@jmjaffe37 Can you take a look please

**Comment by jmjaffe37** [comment]
Looks like the sha256sum links have yet to be updated. I will go through and do them 👍

**Comment by samruddhikhandale** [comment]
This issue is now fixed, thank you! Appreciate the fast response ✨

**Comment by jmjaffe37** [comment]
@samruddhikhandale thank you for noticing that this issue is fixed! I want to apologize that I forgot to update you here once I addressed the problem 😅
