### ISSUE TITLE
JDK/JRE 11 - jdk-11.0.20.1+1 - Upgrade issue

### ISSUE THREAD

**Issue by joe-braley** [microsoft/openjdk#565]
### **_Please refer to the original GitHub issue [here](https://github.com/adoptium/adoptium-support/issues/893#issue-1887595275)._**

***********************

Please provide a brief summary of the bug
Hello,

Downloaded and installed - https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi

We are facing issue during upgrade.

Installed the latest version "11.0.20.101" on top of "11.0.20.8" - Both versions co-exist as shown below:
Co-exists

Tested the following scenarios:
Installed 11.0.20.101 on top of 11.0.20.8 - CO-EXIST
Installed 11.0.20.101 on top of 11.0.19.7 - Upgrades
Installed 11.0.20.8 on top of 11.0.19.7 - Upgrades

Tried the same with x86 as well - https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.20.1_1.msi
Same behavior as x64.
image

Could you please help us with this?

Thank you.

Please provide steps to reproduce where possible
Installed https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20%2B8/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20_8.msi with default selection.

On the same account, installed https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.20.1%2B1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.20.1_1.msi with same default selection.

Both versions co-exist without upgrading to higher version.
Co-exists

Expected Results
It should be upgraded with earlier version like the following:

11.0.20.101 on top of 11.0.19.7 - Upgrades.
11.0.20.8 on top of 11.0.19.7 - Upgrades.

Actual Results
While installing11.0.20.101 on top of 11.0.20.8 it should upgrade, not CO-EXIST.

What Java Version are you using?
What is your operating system and platform?
Windows 10

How did you install Java?
Java is not installed.

Did it work before?
Installed 11.0.20.101 on top of 11.0.19.7 - Upgrades.
Installed 11.0.20.8 on top of 11.0.19.7 - Upgrades.
Did you test with the latest update version?
Yes
Did you test with other Java versions?
No
Relevant log output
No response

**Comment by brunoborges** [comment]
@joe-braley is this still a valid issue?
