### ISSUE TITLE
Bug (Java 21) - sha256sum.txt bug for automatic resolver

### ISSUE THREAD

**Issue by samruddhikhandale** [microsoft/openjdk#568]
**Describe the bug**

Thank you for adding support for Java 21 ✨ 

```
 wget --progress=dot:giga -O sha256sum.txt  https://aka.ms/download-jdk/microsoft-jdk-21-linux-aarch64.tar.gz.sha256sum.txt
```

The contents of the  `sha256sum.txt` file form above ^ command does not match with the contents returned with following command 👇 

```
 wget --progress=dot:giga -O sha256sum.txt  https://aka.ms/download-jdk/microsoft-jdk-21.0.0-linux-aarch64.tar.gz.sha256sum.txt
```

To me, it seems like an issue with the automatic resolver.

**MSFT Build of OpenJDK Version:**

Java 21

**Screenshots, Logs etc**

![Image](https://github.com/microsoft/openjdk/assets/24955913/353cf30b-1f7b-456f-995b-f0b5bd22c46b)

![Image](https://github.com/microsoft/openjdk/assets/24955913/06a32f31-0653-45a8-aed2-a8ea3474efa0)

**Comment by d3r3kk** [comment]
Yes, this is a shortcoming of our release thus far! You are a fast adopter for  sure, thanks for being a keen user of the Microsoft Build of OpenJDK, and for your feedback! 😄 

While we have indeed published the binaries in our [download](https://learn.microsoft.com/en-us/java/openjdk/download) page, we haven't published our ['vanity' links](https://learn.microsoft.com/en-us/java/openjdk/download-major-urls) for JDK21. 

We will have this corrected by EOD (in PST timezone) tomorrow, including links for the `.sha256sum.txt` files that correspond to each binary.

Future releases will have this step incorporated into the initial publish step.

**Comment by joe-braley** [comment]
The Aka links have been updated. Please go ahead and try again, @samruddhikhandale.

**Comment by samruddhikhandale** [comment]
That worked, thank you! 🎉
