### ISSUE TITLE
Debian 12: E: unable to locate package msopenjdk-21

### ISSUE THREAD

**Issue by LearnWebGitHub** [microsoft/openjdk#584]
It's okay on Debian 10.
I've checked the online packages directory, no any msopenjdk in Debian 12 packages directory, is it related?
[Debian 12](https://packages.microsoft.com/debian/12/prod/pool/main/m/)
[Debian 10](https://packages.microsoft.com/debian/10/prod/pool/main/m/)

**Comment by microhobby** [comment]
I wonder if the project is being maintained 🤔, the last release was in January and the website is down with an error: https://www.microsoft.com/openjdk

**Comment by karianna** [comment]
@Luigi96 Can you check for our Jan PSU?

**Comment by d3r3kk** [comment]
I believe we haven't begun publishing to Debian other than 10 - we will look into it shortly and update our scripts as necessary.

**Comment by radutomy** [comment]
Hi, sorry to reopen this but I'm trying to set up msopenjdk on Debian and the package seems to be missing. Followed the instructions from here: https://learn.microsoft.com/en-us/java/openjdk/install#debian-10

```
root@box:~# apt-get install wget lsb-release -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
wget is already the newest version (1.21.3-1+b2).
lsb-release is already the newest version (12.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@box:~# wget https://packages.microsoft.com/config/debian/${lsb_release -rs}/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
-bash: https://packages.microsoft.com/config/debian/${lsb_release -rs}/packages-microsoft-prod.deb: bad substitution

root@box:~# wget https://packages.microsoft.com/config/debian/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
--2024-03-14 10:01:44--  https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.105.221.16, 2603:1062:10:10::1
Connecting to packages.microsoft.com (packages.microsoft.com)|13.105.221.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4304 (4.2K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft-prod.deb               100%[===================================================================================>]   4.20K  --.-KB/s    in 0s

2024-03-14 10:01:45 (142 MB/s) - ‘packages-microsoft-prod.deb’ saved [4304/4304]

root@box:~# ls
packages-microsoft-prod.deb

root@box:~# dpkg -i packages-microsoft-prod.deb
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 10137 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.1-debian12) ...
Setting up packages-microsoft-prod (1.1-debian12) ...
root@box:~# apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://ftp.debian.org/debian bookworm-backports InRelease
Hit:3 http://security.debian.org/debian-security bookworm-security InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Get:5 https://packages.microsoft.com/debian/12/prod bookworm InRelease [3,618 B]
Get:6 https://packages.microsoft.com/debian/12/prod bookworm/main all Packages [342 B]
Get:7 https://packages.microsoft.com/debian/12/prod bookworm/main arm64 Packages [6,183 B]
Get:8 https://packages.microsoft.com/debian/12/prod bookworm/main armhf Packages [5,602 B]
Get:9 https://packages.microsoft.com/debian/12/prod bookworm/main amd64 Packages [33.4 kB]
Fetched 49.2 kB in 0s (104 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

root@box:~# apt install msopenjdk-21
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package msopenjdk-21
```

**Comment by d3r3kk** [comment]
I see the problem. We've not published to anything but Debian 10 yet. When we originally wrote the doc, only 10 was  present in packages.microsoft.com, and since then our team has not kept up to the versions of Debian that Microsoft provides packages for.

Change this line:

```
wget https://packages.microsoft.com/config/debian/$(lsb_release -rs)/packages-microsoft-prod.deb ...
```

to:

```
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
```

...and that will unblock you for now. We will fix it (or communicate otherwise) in time for the April release of the Microsoft Build of OpenJDK.

My apologies for this oversight on my part.

Also, I will look to correct the `wget` line using `lsb-release` so it works successfully out of the box (I'd put the wrong type of bracket in for the substitution I see).

**Comment by radutomy** [comment]
> (I'd put the wrong type of bracket in for the substitution I see).

This one always gets me too.

**Comment by d3r3kk** [comment]
Documentation has been updated. We will do our best to get `bookworm` added to the list of SKUs we target,  I'm hoping it will be in place for the next PSU (mid-April) but it may take us longer.

**Comment by jmjaffe37** [comment]
Quick update: we now support packages all of our msopenjdk packages for Debian 11 and 12 on arcitectures aarch64 and x64. These packages include:

- msopenjdk-11
- msopenjdk-17
- msopenjdk-21 

This means that we will support Debian 9 through 12 going forward (on both aarch64 and x64). You can find updated installation instructions under the "Install on Debian" section of our official download page [here](https://learn.microsoft.com/en-us/java/openjdk/install#install-on-debian).
