### ISSUE TITLE
Unexpected fatal error (Error code : 1)

### ISSUE THREAD

**Issue by Sowicka10** [microsoft/openjdk#593]
I actually cannot describe what was the bug but my game suddenly crashed due to unexpected fatal error. Here is the error audit log :  
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff99b731cc2, pid=19752, tid=19744
#
# JRE version: OpenJDK Runtime Environment Microsoft-28056 (17.0.1+12) (build 17.0.1+12-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-28056 (17.0.1+12-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x131cc2]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by karianna** [comment]
@Sowicka10 Can you please upgrade to 17.0.10 and let us know if you still experience a crash?

**Comment by Sowicka10** [comment]
Hello, I found out what was the problem. I was already upgraded to Java 17
but I still had installed Java 8 Update 401 and I had to change minecraft
java environment folder and then it worked. You don't need to improve
anything ya'll are doing great :)

Dňa št 22. 2. 2024, 2:46 Martijn Verburg ***@***.***>
napísal(a):
