### ISSUE TITLE
Support Nix package manager

### ISSUE THREAD

**Issue by giggio** [microsoft/openjdk#594]
**Describe the solution you'd like**
I'd like to be able to install msopenjdk using Nix.

**Describe alternatives you've considered**
Install using tradicional methods, but this will not work on NixOS.

**Additional context**
https://nixos.org/

**Comment by karianna** [comment]
Hi @giggio - I'd like to understand more about this.  Are you deploying at scale on (Azure) or?

**Comment by giggio** [comment]
Hello @karianna - No, I'm just using it to run Java using Nix. Not on Azure.

**Comment by karianna** [comment]
OK thanks, I'll keep this open until so more folks in the community can weigh in but to set expectations we typically need a significant number of users/customers to invest in a new package manager/installer due to the long term maintenance costs.

**Comment by giggio** [comment]
Ok. I went with the Mozilla one by now.
