### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment: # #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb7f7707eb, pid=8684, tid=9592 # # JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS) # Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64) # Problematic frame: # C  [atio6axx.dll+0x1ce07eb] # # No core dump will be written. Minidumps are not enabled by default on client versions of Windows

### ISSUE THREAD

**Issue by mukaduka1** [microsoft/openjdk#597]
help i just want to use anisotropic filtering on 16x and this is happend
A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb7f7707eb, pid=8684, tid=9592
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0x1ce07eb]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows -its crash report

**Comment by karianna** [comment]
@mukaduka1 Can you please use our latest 17.0.10 and post the result here?
