### ISSUE TITLE
Ubuntu 24.04

### ISSUE THREAD

**Issue by radutomy** [microsoft/openjdk#606]
Ubuntu 24.04 is out - can we get msopendjdk support for it please.

**Comment by karianna** [comment]
ACKing the request, we are discussing internally.

**Comment by brunoborges** [comment]
@radutomy... Our JDK works fine on Ubuntu 24.04, and if you are running our JDK on Ubuntu 24.04 on Azure, you do get support.

Let me know what else you would like to see.

**Comment by radutomy** [comment]
@brunoborges

According to MSFT docs, 24.04 is not supported: https://learn.microsoft.com/en-us/java/openjdk/install#install-on-ubuntu
> Valid values are only '18.04', '20.04', and '22.04'


That is because `msopenjdk` currently only exists on 22.04 repos: https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/ 
It is not pushed to 24.04: https://packages.microsoft.com/ubuntu/24.04/prod/pool/main/m/

**Comment by brunoborges** [comment]
We are still not pushing a DEB package specifically for 24.04, but customers are welcome to download the TAR.GZ and use it directly.

**Comment by m-moris** [comment]
Are there plans to provide packages for Ubuntu 24.04? If so, when are they expected to be available?

**Comment by brunoborges** [comment]
We may use Ubuntu 24.04 for JDK 25 next year.

But no plans to change for the existing images.

**Comment by radutomy** [comment]
> But no plans to change for the existing images.

The choice to not support the latest LTS release from the biggest Linux distro is... interesting.

**Comment by brunoborges** [comment]
We support our JDKs in Ubuntu 24.04 when running on Azure.

We are just not publishing container images out of the box.
Customers are welcome to build their own images and then run on Azure. We will provide support.

**Comment by brunoborges** [comment]
@radutomy I have updated our documentation to provide more information about different versions of Ubuntu:

https://learn.microsoft.com/en-us/java/openjdk/containers#use-a-different-version-of-ubuntu

**Comment by radutomy** [comment]
Hi @brunoborges I am not using Docker nor Microsoft Azure, I just want to install OpenJDK on a standard Ubuntu 24.04 release using a package manager. 24.04 support is still missing from the relevant page https://learn.microsoft.com/en-us/java/openjdk/install#install-on-ubuntu
