### ISSUE TITLE
JVM crash on ARM64 while using Ghidra

### ISSUE THREAD

**Issue by boricj** [microsoft/openjdk#617]
**Describe the bug**

I got a crash of the JVM while using Ghidra:
* Ghidra 11.1 (+Generic.jar built from NationalSecurityAgency/ghidra@76977bd514 dropped inside `Ghidra\patch`, to work around the lack of native components for the ARM64 platform)
* ghidra-delinker-extension 0.4.0

Ghidra was launched through VSCode by debugging my Ghidra extension. No breakpoints were active and no threads were paused at the time of the crash.

**Desktop (please complete the following information):**

Version: Windows 11, 23H2 (10.0.22631 Build 22631)
Device: Windows Dev Kit 2023

**MSFT Build of OpenJDK Version:**

```
openjdk 21.0.1 2023-10-17 LTS
OpenJDK Runtime Environment Microsoft-8526870 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Microsoft-8526870 (build 21.0.1+12-LTS, mixed mode)
```

**To Reproduce:**
Unknown, got the crash once so far at seemingly random.

**Expected behavior**
The JVM shouldn't crash.

**Screenshots, Logs etc**
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff803f40b10, pid=20152, tid=616
#
# JRE version: OpenJDK Runtime Environment Microsoft-8526870 (21.0.1+12) (build 21.0.1+12-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-8526870 (21.0.1+12-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-aarch64)
# Problematic frame:
# C  [d3d9on12.dll+0x50b10]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# c:\Users\jblbe\Documents\Sources\ghidra-delinker-extension\hs_err_pid20152.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Additional context**

Error report file: [hs_err_pid20152.log](https://github.com/user-attachments/files/16133640/hs_err_pid20152.log)

**Comment by brianjstafford** [comment]
Hi @boricj. This looks like a bug in DirectX. Please file an issue using the Feedback Hub app (https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) for the Windows team to take a look at.

**Comment by boricj** [comment]
Issue submitted to the Feedback Hub: https://aka.ms/AAr9t6j
