### ISSUE TITLE
Azure App Service is throwing the error while warming up container never started even if set the WEBSITES_PORT and enabled the WEBSITES_CONTAINER_START_TIME_LIMIT to 7200

### ISSUE THREAD

**Issue by pedrolozano** [microsoft/openjdk#618]
**Describe the bug**
while warming up i had different SIGSEGV errors in 11 containers, all had been deployed and working fine but started failling about 1 week ago.  I had tried redeploying 1 of them but didn´t work either. i had tried with different parent pom versions, but still different errors triggered, it works in local fine. it is just after the deployment , in the warming up step while fails.

one sample here:
2024-07-08T19:25:22.136278355Z #  SIGSEGV (0xb) at pc=0x00007ea0e9090a72 (sent by kill), pid=126, tid=127
2024-07-08T19:25:22.136462772Z #
2024-07-08T19:25:22.136699193Z # JRE version: OpenJDK Runtime Environment Microsoft-9388408 (17.0.11+9) (build 17.0.11+9-LTS)
2024-07-08T19:25:22.136899611Z # Java VM: OpenJDK 64-Bit Server VM Microsoft-9388408 (17.0.11+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
2024-07-08T19:25:22.137099729Z # Problematic frame:
2024-07-08T19:25:22.138007610Z # J 4576 c2 java.net.URL.<init>(Ljava/net/URL;Ljava/lang/String;Ljava/net/URLStreamHandler;)V java.base@17.0.11 (543 bytes) @ 0x00007ea0e9090a72 [0x00007ea0e908fcc0+0x0000000000000db2]
2024-07-08T19:25:22.138222029Z #

**Desktop (please complete the following information):**

OS & version Linux : 
[azureLog07082024.log](https://github.com/user-attachments/files/16133819/azureLog07082024.log)
[azureLog05072024.log](https://github.com/user-attachments/files/16133820/azureLog05072024.log)
Unix 5.15.153.1

**MSFT Build of OpenJDK Version:**
JRE version: OpenJDK Runtime Environment Microsoft-9388408 (17.0.11+9) (build 17.0.11+9-LTS)

The output from `java --version`

**To Reproduce:**

1. Use 		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.1-SNAPSHOT</version>
2. deploy it
3. wait until sevice stops
4. send a request to warm it up, the error appears

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by brianjstafford** [comment]
Hi @pedrolozano. Would it be possible for you to attach a full HotSpot error log file?

**Comment by brunoborges** [comment]
@pedrolozano have you opened an Azure Support ticket already? If not, please do.

**Comment by pedrolozano** [comment]
Hi , thanks for the reply yes the ticket number is : 2407090040000706  i am not sure how i can get that error file but i am trying with this ones: 
[zip (3).zip](https://github.com/user-attachments/files/16136844/zip.3.zip)
[java_error_customeraccountsservice_lw1mdlwk0000HX_98.log.txt](https://github.com/user-attachments/files/16136999/java_error_customeraccountsservice_lw1mdlwk0000HX_98.log.txt)
Thans in advance !

**Comment by jvano** [comment]
Hi

For any Azure related issue, please open an Azure support request:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by brunoborges** [comment]
Closing for now while we look at this through Azure Support channel.

**Comment by pedrolozano** [comment]
Thanks I received a request to increase the resources (CPU) now is there any way tool or document to compare different options  to host Spring Boot apps ? and decide which one to choose ? I was evaluating different ones but charged me on the testing phase. Thanks in advance

**Comment by brunoborges** [comment]
You can check this documentation:

https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/service-for-java-comparison
