### ISSUE TITLE
Tlauncher wont launch minecraft 1.17 

### ISSUE THREAD

**Issue by manan75** [microsoft/openjdk#62]
**Describe the bug**
Minecraft 1.17 crashes after trying to launch it from tlaucnher. All previous versions work fine. The drivers are also up to date
**To Reproduce**
Steps to reproduce the behavior: Not sure if it will be able to reproduce easily. Since prev versions of Minecraft work I'm not sure what is the actual problem. I checked the drivers, they are up to date. My pc model is from 2016 so i suppose they don't give updates on drivers anymore
1. Open the tlauncher
2. Select ver 1.17
3. click enter game

**Expected behavior**
Launcher disappears and after a while fails to launch the game and shows an error screen.

**Screenshots**
![Screenshot 2021-06-10 175454](https://user-images.githubusercontent.com/85684429/121524618-19bef100-ca15-11eb-9992-6fee9c2f78cf.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 

**Additional context**
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff803763760, pid=13148, tid=11224
#
# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ff803763760
[error occurred during error reporting (printing problematic frame), id 0xc0000005, EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff803763f10]

# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by Suvichan2005** [comment]
Exact same problem here

**Comment by manan75** [comment]
> Exact same problem here

You're getting the same problematic frame?

**Comment by karianna** [comment]
@manan75 - Are you able to submit this issue over at https://bugs.mojang.com/projects/MC/issues/ - the Mojang folks will take the first pass at Triage.  For the others on the thread, I'd recommend upvoting @manan75's issue over on the Mojang issue tracker :-)

**Comment by manan75** [comment]
> @manan75 - Are you able to submit this issue over at https://bugs.mojang.com/projects/MC/issues/ - the Mojang folks will take the first pass at Triage. For the others on the thread, I'd recommend upvoting @manan75's issue over on the Mojang issue tracker :-)

How do i submit the issue to mojang. I could not find any way to report there.

**Comment by karianna** [comment]
@manan75 - Thanks!  There's a Login in the top right-hand corner.  You may need to create an account first to see the issue submission option.

**Comment by karianna** [comment]
@manan75 - How did you get on?

**Comment by violine1101** [comment]
TLauncher is a pirated version of Minecraft and not supported by Mojang in any way. Please purchase Minecraft if you want to play it.
