### ISSUE TITLE
provide openjdk-22

### ISSUE THREAD

**Issue by soloturn** [microsoft/openjdk#622]
the download page does not list newest openjdk for aarch64 , can you please provide openjdk-23 which comes out in a week or so?

**Comment by karianna** [comment]
Hi there, we are only publicly releasing LTS builds at this time.  Is there a particular use case you have that you were looking to use Java 22 for?

**Comment by soloturn** [comment]
@karianna support for java ffi lol

**Comment by karianna** [comment]
For non LTS releases we'd recommend Eclipse Temurin binaries from adoptium.net

**Comment by soloturn** [comment]
you guys mind helping out adoptium please then to properly publish the newest package on e.g. winget: https://github.com/adoptium/temurin-build/issues/3071 ? i see you once commented.
