### ISSUE TITLE
choco install of openjdk arm not obvious

### ISSUE THREAD

**Issue by soloturn** [microsoft/openjdk#624]
installing the arm version of openjdk is not obvious.  can you please assure that
```
choco install openjdk
```
installes the correct binary?

currently it downloads the x64 version for both, openjdk, and microsoft-openjdk:
```
Downloading openjdk 64 bit
  from 'https://download.java.net/java/GA/jdk21/fd2272bbf8e04c3dbaee13770090416c/35/GPL/openjdk-21_windows-x64_bin.zip'

Downloading microsoft-openjdk 64 bit
  from 'https://aka.ms/download-jdk/microsoft-jdk-21.0.4-windows-x64.msi'

```

**Comment by karianna** [comment]
@soloturn - This really is a request for the chocolaty team. It's not something that the Java Engineering Group at Microsoft has capacity to support I'm afraid!
