### ISSUE TITLE
openjdk should not set JAVA_HOME

### ISSUE THREAD

**Issue by soloturn** [microsoft/openjdk#626]
JAVA_HOME is an unnecessary variable, as this can be detected from the running java program. setting it causes subsequent errors, like the microsoft vscode java plugin thinks all of a sudden JAVA_HOME should be used to detect an installed java, instead of just looking into the path, resp running java.

but, openjdk should set a link so the path can be set sometimes to java-21 and java-17 with ease, e.g. /program-files/openjdk-21 pointing to /program-files/Microsoft\jdk-21.0.4.7-hotspot\bin

**Comment by karianna** [comment]
We typically recommend SDKMan or jenv to resolve being able to select between multiple JVMs and having JAVA_HOME set appropriately each time.

**Comment by soloturn** [comment]
how could the use of sdkman or jenv influence if the microsoft openjdk package sets java_home on install and should not set it?

**Comment by karianna** [comment]
@soloturn - Do you mean our MSI installer that sets this variable?

**Comment by soloturn** [comment]
i am not 100% sure where it came from. if i recall correctly i used winget to install, so i assumed it is in the msi.

**Comment by karianna** [comment]
Assigned to @brunoborges as part of his standardization for Windows installers investigation.  To set expectations, there's no short term changes planned, but we are looking to see if the OpenJDK is willing to align on an approach here.

**Comment by soloturn** [comment]
i installed zulu jdk recently, and the installer asked if i want to set java_home. so it is definitvely in the installer, not in openjdk.

**Comment by brunoborges** [comment]
@soloturn when you installed Zulu, did you install with the graphical interface of the MSI, or did you install through WinGet?

The MS JDK MSI installer graphical UI does ask if the user wants to set `JAVA_HOME`. But when one installs with `winget`, it is enabled by default, as that is the intent of the majority of users. Advanced users may want to use a different installation method

**Comment by soloturn** [comment]
i installed through winget, and it opened the window to choose. so it was
kind of both?
