### ISSUE TITLE
retrieving windows folders broken, APPDATA

### ISSUE THREAD

**Issue by soloturn** [microsoft/openjdk#628]
making portable java code which stores its files in the correct locations for different operating system is a challeng. as one user called it at the tiny dirs-dev library trying to implement these directories: https://github.com/dirs-dev/directories-jvm/issues/49. The internet is full of suggestions how to do it, most of them failed at some point.

At the end of the day, why on earth people think it is necessary to access a native windows system call to find something that trivial as `APPDATA` or `LOCALAPPDATA` in a reliable way?

Just some random links:

* Using jna: https://github.com/harawata/appdirs/blob/master/src/main/java/net/harawata/appdirs/impl/ShellFolderResolver.java
* jna in graalvm: https://stackoverflow.com/questions/77323544/graalvm-and-jna-dependency, 2024

Would you please be so kind to make a statement from Microsoft point of view how to properly and reliably retrieve the values with openjdk-21, WITHOUT using native , and for which windows operating system versions this is valid?

**Comment by karianna** [comment]
I'm sympathetic to the challenges here (I've read the long thread in the original dirs-dev issue tracker). However, this is not an issue related to the Microsoft Build of OpenJDK and so I'm closing this item here.  In a *personal* capacity, I'll reply on the dirs-dev thread to see if I can better understand the issue.
