### ISSUE TITLE
minecraft won't open at all (minecraft)

### ISSUE THREAD

**Issue by emiwig** [microsoft/openjdk#63]
when i try to open minecraft through the launcher it won't open. it goes to the loading screen sometimes and then it crashes, but sometimes it opens to the select screen but crashes instedly. 
and i think my drivers are up to date (85% sure)

what i did when minecraft crashed
1, i open the launcher
2, i clicked "play"
3, some times it goes to load the game and sometimes it just crashes

Screenshots:
https://user-images.githubusercontent.com/85704320/121582502-6283a380-ca2f-11eb-8763-df688ec5ac2c.png

OS: windows 10 pro
web browser: crome

the crash report
https://github.com/microsoft/openjdk/files/6633822/hs_err_pid15936.log

**Comment by karianna** [comment]
@emiwig - Are you able to submit this issue over at https://bugs.mojang.com/projects/MC/issues/ - the Mojang folks will take the first pass at Triage :-)

**Comment by emiwig** [comment]
yea i am able to submit there

**Comment by karianna** [comment]
@emiwig Do you have a link to the issue you submitted?

**Comment by karianna** [comment]
@emiwig Do you have a link to the issue you submitted?

**Comment by Marcono1234** [comment]
Looks like they reported it as [MC-228531](https://bugs.mojang.com/browse/MC-228531) (private report), but then edited their report to state that the issue has been solved. Therefore we have resolved the report as Invalid (and did not get any response from them back).
