### ISSUE TITLE
Game crashes in Launcher

### ISSUE THREAD

**Issue by tniel14** [microsoft/openjdk#66]
[hs_err_pid728.log](https://github.com/microsoft/openjdk/files/6645134/hs_err_pid728.log)

When I hit Play in the Minecraft 1.17 launcher, it starts to load then it crashes and returns saying there was an error.
I have reinstalled the game, updated drivers etc and still cannot get the game to work. When I have previously played, I've had no trouble and I have not installed any new Hardware since I last played.

**Comment by karianna** [comment]
@tniel14 Are you able to submit this issue over at https://bugs.mojang.com/projects/MC/issues/ - the Mojang folks will take the first pass at Triage :-)

**Comment by KinFireRain** [comment]
I'm having the same issue. Microsoft says it's NOT a bug.
They gave me their typical try this, then this, then we don't know and don't care email response

**Comment by karianna** [comment]
> I'm having the same issue. Microsoft says it's NOT a bug.
> They gave me their typical try this, then this, then we don't know and don't care email response

@KinFireRain - I see you've opened your own issue on this repo, so I'll follow up with you there :-)

**Comment by karianna** [comment]
@tniel14 or @KinFireRain are you able to post back here a link to the Issue you opened up on Mojang's issue tracker?

**Comment by Marcono1234** [comment]
Looks like tniel14 reported it as [MC-228876](https://bugs.mojang.com/browse/MC-228876) (private report). We have now reopened that report (see also https://github.com/microsoft/openjdk/issues/68#issuecomment-869831545).
