### ISSUE TITLE
Minecraft 1.17 crashes when using streamlabs game capture

### ISSUE THREAD

**Issue by bigseabite** [microsoft/openjdk#69]
When Streamlabs is open and attempting to record Minecraft using game capture, Minecraft will crash. I have only had this issue in Minecraft 1.17. Snapshots, modded, and older full versions are not affected and do not crash with Streamlabs.
There are a few results for this happening to other people when I look it up, but none were solved.
Crash log (attached at the bottom) told me to report here

**To Reproduce**
1. Play Minecraft 1.17. You can be anywhere in the game (menu, single player world, server, ect)
2. Open Streamlabs OBS (https://streamlabs.com/)
3. Use Game Capture on a specific window to capture Minecraft 1.17

**Expected behavior**
The game will crash and take you to the Minecraft launcher, with the crash error screen. Streamlabs will not have any issues.

**Crash Log**
[hs_err_pid13736.log](https://github.com/microsoft/openjdk/files/6659227/hs_err_pid13736.log)

**Comment by brstaffoMS** [comment]
Hi @bigseabite! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/ ? The folks at Mojang will take the first look. Thanks!

**Comment by bigseabite** [comment]
@brstaffoMS reported there!

**Comment by karianna** [comment]
> @brstaffoMS reported there!

@bigseabite Thank you!  Are you able to link to that issue here?

**Comment by bigseabite** [comment]
> > @brstaffoMS reported there!
> 
> @bigseabite Thank you! Are you able to link to that issue here?

https://bugs.mojang.com/browse/MC-229195

**Comment by karianna** [comment]
Thanks! Closing this to avoid duplication/confusion, we'll collaborate with Mojang on their tracker.

**Comment by zavarana-uhorka** [comment]
i have the same problem
