### ISSUE TITLE
Minecraft 顯示有問題

### ISSUE THREAD

**Issue by 3016052** [microsoft/openjdk#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![195873968_913375389524524_4754270371905922385_n](https://user-images.githubusercontent.com/85981136/122161532-78b4b800-cea4-11eb-9227-5190f061a722.jpg)

**Comment by karianna** [comment]
@3016052 Hi there - I'm not sure what the issue is that you are experiencing?  Can you give us some more details?

**Comment by 3016052** [comment]
就是我的Minecraft進去之後，方塊很常變成全黑的或者是變成紅綠色，最後還可以看的到方塊下的東西(方塊變透明)

**Comment by karianna** [comment]
@3016052 - Thanks for your response.  I had to use Google Translate, I hope this is correct?

_In Minecraft, the blocks often turn all black or red-green, and what's under the blocks goes funny as well (the blocks become transparent)._

I suspect this is an issue with the Minecraft client (as opposed to the Java that works under the hood). 

Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/ ? The folks at Mojang will take the first look. Thanks!

**Comment by 3016052** [comment]
Thinks for your recieve.  I will try it later.

**Comment by karianna** [comment]
> Thinks for your recieve. I will try it later.

Thank you!  If you do raise an issue over there then please do paste the link here and we can also follow up if need be.

**Comment by karianna** [comment]
Hi @3016052 - How did you get on?  Is there a link to the issue you can post back here?
