### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zavarana-uhorka** [microsoft/openjdk#78]
everytime i alttab minecraft to obs studio it just crashes idk whats the problem please help here is the crash log https://pastebin.com/27A50Z8c

**Comment by brstaffoMS** [comment]
Hi @zavarana-uhorka! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look at this issue. Thanks!

**Comment by karianna** [comment]
Likely duplicate of #69

**Comment by karianna** [comment]
Please also see https://bugs.mojang.com/browse/MC-229195
