### ISSUE TITLE
vm_info on Windows not stating who built the JVM

### ISSUE THREAD

**Issue by karianna** [microsoft/openjdk#84]
VM Crash reports have this in their logs:

`vm_info: OpenJDK 64-Bit Server VM (16.0.1+9) for windows-amd64 JRE (16.0.1+9), built on Apr 21 2021 17:16:40 by "" with MS VC++ 16.8 (VS2019)`

Should probably say this

`vm_info: OpenJDK 64-Bit Server VM (16.0.1+9) for windows-amd64 JRE (16.0.1+9), built on Apr 21 2021 17:16:40 by **"Microsoft Corporation Ltd."** with MS VC++ 16.8 (VS2019)` or something close to that

**Comment by d3r3kk** [comment]
Seems to only be present for Windows builds? See [here](https://github.com/openjdk/jdk17u/blob/e6f9d19c8762750db3f4d5b33e2b576bce66ab2a/src/hotspot/share/runtime/abstract_vm_version.cpp#L276) for where it gets injected into the report and [here](https://github.com/openjdk/jdk17u/blob/9ad19f7838e6f6e128583c191c5507c1e2bd5083/make/ide/visualstudio/hotspot/src/classes/build/tools/projectcreator/BuildConfig.java#L224) for where it gets set (I cannot seem to find anywhere else it is being set at the moment).

The value [_is used_ in a few places though](https://github.com/openjdk/jdk17u/search?q=internal_vm_info_string&type=code) so we probably should set it.

**Comment by d3r3kk** [comment]
Looks like could accomplish this by adding more to the `configure` parameter set, specifically `--with-extra-cxxflags=DHOTSPOT_BUILD_USER="Microft Corporation Ltd."`

**Comment by brunoborges** [comment]
@d3r3kk was that flag added for the April builds?
