### ISSUE TITLE
Minecraft Crashes When Trying To Play Latest Release 1.17.1 - Can't Even Launch Game

### ISSUE THREAD

**Issue by EthanMcCracken** [microsoft/openjdk#98]
A fatal error has been detected by the Java Runtime Environment:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=15900, tid=10544

JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
Problematic frame:
C  0x0000000000000000

No core dump will be written. Minidumps are not enabled by default on client versions of Windows

If you would like to submit a bug report, please visit:
https://github.com/microsoft/openjdk/issues
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug

**Comment by EthanMcCracken** [comment]
Exit Code 0

**Comment by karianna** [comment]
Hi @EthanMcCracken! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look at this issue. Thanks!
