### ISSUE TITLE
game crashes when trying to launch java 1.17

### ISSUE THREAD

**Issue by BobDylanSamsung** [microsoft/openjdk#99]
when I try and launch Minecraft the game crashes and reports exit code 0.

I have uninstalled and re-installed Minecraft which didn't fix the problem.

This is the crash report:

![image](https://user-images.githubusercontent.com/72124168/125943907-6fc280d6-77b3-461b-bfad-6d5ce1afcfa0.png)

Thanks in advance

**Comment by brstaffoMS** [comment]
Hi @BobDylanSamsung! Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!
